package dv;

import androidx.credentials.playservices.controllers.CredentialProviderBaseController;
import androidx.recyclerview.widget.m0;
import com.adyen.checkout.googlepay.AllowedCardNetworks;
import com.app.tgtg.model.local.AppConstants;
import com.appsflyer.AFInAppEventParameterName;
import com.google.android.gms.dynamite.descriptors.com.google.android.gms.measurement.dynamite.ModuleDescriptor;
import com.tgtg.componentlibrary.component.chip.model.ChipSemanticsKt;
import org.bouncycastle.asn1.BERTags;
import org.bouncycastle.math.Primes;
import org.jetbrains.annotations.NotNull;
import v0.n;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* JADX INFO: compiled from: r8-map-id-bad8e3e1b75e2d3fd72c92f1b960553adb24fef824cc9e98cee450b85845d4c2 */
/* JADX INFO: loaded from: classes2.dex */
public final class a {
    private static final /* synthetic */ a80.a $ENTRIES;
    private static final /* synthetic */ a[] $VALUES;

    @NotNull
    private final String value;
    public static final a ACTION = new a("ACTION", 0, "Action");
    public static final a AUTO_SCROLLED_TO = new a("AUTO_SCROLLED_TO", 1, "Auto_Scrolled_To");
    public static final a ACTION_TYPE = new a("ACTION_TYPE", 2, "Action_Type");
    public static final a ADDRESS_PREFILLED = new a("ADDRESS_PREFILLED", 3, "Address_Prefilled");
    public static final a AF_QUANTITY = new a("AF_QUANTITY", 4, AFInAppEventParameterName.QUANTITY);
    public static final a AF_CONTENT_TYPE = new a("AF_CONTENT_TYPE", 5, AFInAppEventParameterName.CONTENT_TYPE);
    public static final a AF_CURRENCY = new a("AF_CURRENCY", 6, AFInAppEventParameterName.CURRENCY);
    public static final a AF_ORDER_ID = new a("AF_ORDER_ID", 7, "af_order_id");
    public static final a AF_REVENUE = new a("AF_REVENUE", 8, AFInAppEventParameterName.REVENUE);
    public static final a ANSWER = new a("ANSWER", 9, "Answer");
    public static final a ANSWERS = new a("ANSWERS", 10, "Answers");
    public static final a APP_STORE = new a("APP_STORE", 11, "AppStore");
    public static final a ATTACHMENT = new a("ATTACHMENT", 12, "Attachment");
    public static final a AVAILABLE_BACKUP_DONATIONS = new a("AVAILABLE_BACKUP_DONATIONS", 13, "Available_Backup_Donations");
    public static final a AVAILABLE_CUSTOM_DAYS = new a("AVAILABLE_CUSTOM_DAYS", 14, "Available_Custom_Days");
    public static final a AVAILABLE_DAYS_TO_COLLECT = new a("AVAILABLE_DAYS_TO_COLLECT", 15, "Available_Days_To_Collect");
    public static final a AVAILABLE_ITEM_COUNT = new a("AVAILABLE_ITEM_COUNT", 16, "Available_Item_Count");
    public static final a AVAILABLE_ON_MONDAY = new a("AVAILABLE_ON_MONDAY", 17, "Available_On_Monday");
    public static final a AVAILABLE_ON_TUESDAY = new a("AVAILABLE_ON_TUESDAY", 18, "Available_On_Tuesday");
    public static final a AVAILABLE_ON_WEDNESDAY = new a("AVAILABLE_ON_WEDNESDAY", 19, "Available_On_Wednesday");
    public static final a AVAILABLE_ON_THURSDAY = new a("AVAILABLE_ON_THURSDAY", 20, "Available_On_Thursday");
    public static final a AVAILABLE_ON_FRIDAY = new a("AVAILABLE_ON_FRIDAY", 21, "Available_On_Friday");
    public static final a AVAILABLE_ON_SATURDAY = new a("AVAILABLE_ON_SATURDAY", 22, "Available_On_Saturday");
    public static final a AVAILABLE_ON_SUNDAY = new a("AVAILABLE_ON_SUNDAY", 23, "Available_On_Sunday");
    public static final a AVAILABLE_PLANNED_DONATIONS = new a("AVAILABLE_PLANNED_DONATIONS", 24, "Available_Planned_Donations");
    public static final a AVAILABLE_PRIMARY_DONATIONS = new a("AVAILABLE_PRIMARY_DONATIONS", 25, "Available_Primary_Donations");
    public static final a AVAILABLE_STOCK = new a("AVAILABLE_STOCK", 26, "Available_Stock");
    public static final a AVAILABLE_FILTERS = new a("AVAILABLE_FILTERS", 27, "Available_Filters");
    public static final a AVAILABLE_ITEMS = new a("AVAILABLE_ITEMS", 28, "Available_Items");
    public static final a BAG_ALERTS = new a("BAG_ALERTS", 29, "Bag_Alerts");
    public static final a BANNER_TYPE = new a("BANNER_TYPE", 30, "Banner_Type");
    public static final a BASKET_ID = new a("BASKET_ID", 31, "Basket_Id");
    public static final a BOUGHT_ANYTHING_ELSE = new a("BOUGHT_ANYTHING_ELSE", 32, "Bought_Anything_Else");
    public static final a BRACKET = new a("BRACKET", 33, "Bracket");
    public static final a BRAZE_EXTERNAL_USER_ID = new a("BRAZE_EXTERNAL_USER_ID", 34, "Braze_External_User_Id");
    public static final a BUCKET = new a("BUCKET", 35, "Bucket");
    public static final a BUCKETS_SHOWN = new a("BUCKETS_SHOWN", 36, "Buckets_Shown");
    public static final a C2B_REFERRAL_CARD_SHOWN = new a("C2B_REFERRAL_CARD_SHOWN", 37, "C2B_Referral_Card_Shown");
    public static final a CALENDAR_OPTIN_STATUS = new a("CALENDAR_OPTIN_STATUS", 38, "Calendar_Optin_Status");
    public static final a CANCELLING_ENTITY = new a("CANCELLING_ENTITY", 39, "Cancelling_Entity");
    public static final a CAMERA_PHOTO_COUNT = new a("CAMERA_PHOTO_COUNT", 40, "Camera_Photo_Count");
    public static final a CATEGORY = new a("CATEGORY", 41, "Category");
    public static final a CHARITY_IS_AVAILABLE = new a("CHARITY_IS_AVAILABLE", 42, "Charity_Is_Available");
    public static final a CHARITY_COUNTRY = new a("CHARITY_COUNTRY", 43, "charity_country");
    public static final a CHARITY_LOGIN_SECTION = new a("CHARITY_LOGIN_SECTION", 44, "Charity_Login_Section");
    public static final a CHANGE_AVAILABLE = new a("CHANGE_AVAILABLE", 45, "Change_Available");
    public static final a CHECKOUT_ERROR_CAUSE = new a("CHECKOUT_ERROR_CAUSE", 46, "Checkout_Error_Cause");
    public static final a CHURNED_REACTIVATION_PURCHASE = new a("CHURNED_REACTIVATION_PURCHASE", 47, "Churned_Reactivation_Purchase");
    public static final a CLICKED = new a("CLICKED", 48, "Clicked");
    public static final a CLICK_FROM = new a("CLICK_FROM", 49, "Click_From");
    public static final a COLLECTION_TYPE = new a("COLLECTION_TYPE", 50, "Collection_Type");
    public static final a CONTENT_DESCRIBED = new a("CONTENT_DESCRIBED", 51, "Content_Described");
    public static final a CORRELATION_ID = new a("CORRELATION_ID", 52, "Correlation_Id");
    public static final a COUNT_SPECIAL_REWARDS = new a("COUNT_SPECIAL_REWARDS", 53, "countSpecialRewards");
    public static final a COUNT_TAGS_SEEN = new a("COUNT_TAGS_SEEN", 54, "Count_Tags_Seen");
    public static final a COUNT_INITIAL_TAGS_VISIBLE = new a("COUNT_INITIAL_TAGS_VISIBLE", 55, "Count_Initial_Tags_Visible");
    public static final a CREATED_AT = new a("CREATED_AT", 56, "Created_At");
    public static final a CURRENCY = new a("CURRENCY", 57, "Currency");
    public static final a CURRENT_DISTANCE_KM_CHOSEN = new a("CURRENT_DISTANCE_KM_CHOSEN", 58, "Current_Distance_Km_Chosen");
    public static final a CURRENT_STATE = new a("CURRENT_STATE", 59, "Current_State");
    public static final a CUSTOM_DAYS_CLOSED_FROM = new a("CUSTOM_DAYS_CLOSED_FROM", 60, "Custom_Days_Closed_From");
    public static final a DAILY_REMINDER = new a("DAILY_REMINDER", 61, "Daily_Reminder");
    public static final a DAY = new a("DAY", 62, "Day");
    public static final a DAY_PLANNED_DONATIONS = new a("DAY_PLANNED_DONATIONS", 63, "Day_Planned_Donations");
    public static final a DAYS_SINCE_LAST_PURCHASE = new a("DAYS_SINCE_LAST_PURCHASE", 64, "Days_Since_Last_Purchase");
    public static final a DIRECTIONS = new a("DIRECTIONS", 65, "Directions");
    public static final a DISCOUNT_OR_VOUCHER_AVAILABLE = new a("DISCOUNT_OR_VOUCHER_AVAILABLE", 66, "Discount_Or_Voucher_Available");
    public static final a DISCOUNT_USED = new a("DISCOUNT_USED", 67, "Discount_Used");
    public static final a DONATION_CANCELLED = new a("DONATION_CANCELLED", 68, "Donation_Cancelled");
    public static final a DONATION_COLLECTION_INSTRUCTIONS = new a("DONATION_COLLECTION_INSTRUCTIONS", 69, "Donation_Collection_Instructions");
    public static final a DONATION_COLLECTION_START_TIME = new a("DONATION_COLLECTION_START_TIME", 70, "Collection_Start_Time");
    public static final a DONATION_COLLECTION_TIME_UPDATED = new a("DONATION_COLLECTION_TIME_UPDATED", 71, "Collection_Time_Updated");
    public static final a DONATION_FOOD_CATEGORIES = new a("DONATION_FOOD_CATEGORIES", 72, "Donation_Food_Categories");
    public static final a DONATION_INVENTORY_UPDATES = new a("DONATION_INVENTORY_UPDATES", 73, "Donation_Inventory_Updates");
    public static final a DONATION_NUMBER_OF_ITEMS = new a("DONATION_NUMBER_OF_ITEMS", 74, "Donation_Number_Of_Items");
    public static final a DONATION_UPDATED_STATUS = new a("DONATION_UPDATED_STATUS", 75, "Donations_Updated_Status");
    public static final a DONATION_WINDOW_LENGTH = new a("DONATION_WINDOW_LENGTH", 76, "Donation_Window_Length");
    public static final a DONATIONS_CANCELLATIONS = new a("DONATIONS_CANCELLATIONS", 77, "Donations_Cancellations");
    public static final a DONATIONS_COLLECTION_TIME_UPDATES = new a("DONATIONS_COLLECTION_TIME_UPDATES", 78, "Donations_Collection_Time_Updates");
    public static final a DONATIONS_INVENTORY_UPDATES = new a("DONATIONS_INVENTORY_UPDATES", 79, "Donations_Inventory_Updates");
    public static final a DEEPLINK_CAMPAIGN_ID = new a("DEEPLINK_CAMPAIGN_ID", 80, "deeplink_campaign_id");
    public static final a DEEPLINK_SOURCE = new a("DEEPLINK_SOURCE", 81, "deeplink_source");
    public static final a DEEPLINK_TYPE = new a("DEEPLINK_TYPE", 82, "Deeplink_Type");
    public static final a DELIVERY_AVAILABLE = new a("DELIVERY_AVAILABLE", 83, "Delivery_Available");
    public static final a DELIVERY_HAS_STOCK = new a("DELIVERY_HAS_STOCK", 84, "Delivery_Has_Stock");
    public static final a DISCOVER = new a(AllowedCardNetworks.DISCOVER, 85, "Discover");
    public static final a DISCOVER_BUCKET = new a("DISCOVER_BUCKET", 86, "Discover_Bucket");
    public static final a DISTANCE_KM = new a("DISTANCE_KM", 87, "Distance_Km");
    public static final a DYNAMIC_ITEM = new a("DYNAMIC_ITEM", 88, "Dynamic_Item");
    public static final a EMAIL_OPTIN_STATUS = new a("EMAIL_OPTIN_STATUS", 89, "Email_Optin_Status");
    public static final a ERROR_TYPE = new a("ERROR_TYPE", 90, "error_type");
    public static final a EXCEPTION = new a("EXCEPTION", 91, "Exception");
    public static final a EXISTS = new a("EXISTS", 92, "Exists");
    public static final a EXPECTED_DATE_COLLECTION = new a("EXPECTED_DATE_COLLECTION", 93, "Expected_Date_Collection");
    public static final a EXPECTED_ENDING_TIME_COLLECTION = new a("EXPECTED_ENDING_TIME_COLLECTION", 94, "Expected_Ending_Time_Collection");
    public static final a EXPECTED_STARTING_TIME_COLLECTION = new a("EXPECTED_STARTING_TIME_COLLECTION", 95, "Expected_Starting_Time_Collection");
    public static final a EXPLORE_WEEK_AFTER = new a("EXPLORE_WEEK_AFTER", 96, "Explore_Week_After");
    public static final a EXPLORE_WEEK_BEFORE = new a("EXPLORE_WEEK_BEFORE", 97, "Explore_Week_Before");
    public static final a FB_ITEM_ID = new a("FB_ITEM_ID", 98, "item_id");
    public static final a FB_ITEM_NAME = new a("FB_ITEM_NAME", 99, "item_name");
    public static final a FB_ITEM_CATEGORY = new a("FB_ITEM_CATEGORY", 100, "item_category");
    public static final a FB_PRICE = new a("FB_PRICE", 101, "price");
    public static final a FB_QUANTITY = new a("FB_QUANTITY", 102, "quantity");
    public static final a FB_AFFILIATION = new a("FB_AFFILIATION", 103, "affiliation");
    public static final a FB_TRANSACTION_ID = new a("FB_TRANSACTION_ID", 104, "transaction_id");
    public static final a FB_VALUE = new a("FB_VALUE", 105, "value");
    public static final a FB_CURRENCY = new a("FB_CURRENCY", 106, "currency");
    public static final a FB_ITEMS = new a("FB_ITEMS", 107, "items");
    public static final a FIRST_PURCHASE = new a("FIRST_PURCHASE", 108, "First_Purchase");
    public static final a FOOD_QUALITY = new a("FOOD_QUALITY", 109, "Food_Quality");
    public static final a FOOD_VARIETY = new a("FOOD_VARIETY", 110, "Food_Variety");
    public static final a FREE_DELIVERY_THRESHOLD = new a("FREE_DELIVERY_THRESHOLD", 111, "Free_Delivery_Threshold");
    public static final a FREE_TEXT_ANSWER = new a("FREE_TEXT_ANSWER", 112, "Free_Text_Answer");
    public static final a FOOD_QUANTITY = new a("FOOD_QUANTITY", 113, "Food_Quantity");
    public static final a FUTURE_ITEM = new a("FUTURE_ITEM", 114, "Future_Item");
    public static final a GENERAL_INFO = new a("GENERAL_INFO", 115, "GeneralInfo");
    public static final a GPS_ENABLED = new a("GPS_ENABLED", 116, "GPS_Enabled");
    public static final a GALLERY_PHOTO_COUNT = new a("GALLERY_PHOTO_COUNT", 117, "Gallery_Photo_Count");
    public static final a HAS_DEFAULT_PAYMENT_METHOD = new a("HAS_DEFAULT_PAYMENT_METHOD", 118, "Has_Default_Payment_Method");
    public static final a HAS_PURCHASE_LIMIT = new a("HAS_PURCHASE_LIMIT", 119, "Has_Purchase_Limit");
    public static final a HAS_RESERVATION = new a("HAS_RESERVATION", 120, "Has_Reservation");
    public static final a HAS_SEARCH = new a("HAS_SEARCH", 121, "Has_Search");
    public static final a HAS_SPECIAL_OFFERS = new a("HAS_SPECIAL_OFFERS", 122, "Has_Special_Offers");
    public static final a HAS_STOCK = new a("HAS_STOCK", AppConstants.RESULT_CODE_ORDER_CANCELLED, "Has_Stock");
    public static final a HAS_SUGGESTION = new a("HAS_SUGGESTION", 124, "Has_Suggestion");
    public static final a HAS_TIME_FILTER = new a("HAS_TIME_FILTER", 125, "Has_Time_Filter");
    public static final a HERO_COMPONENT = new a("HERO_COMPONENT", 126, "Hero_Component");
    public static final a HIDE_SOLD_OUT = new a("HIDE_SOLD_OUT", 127, "Hide_Sold_Out");
    public static final a HAS_ADDED_HOME_ADDRESS = new a("HAS_ADDED_HOME_ADDRESS", 128, "Has_Added_Home_Address");
    public static final a HAS_ADDED_WORK_ADDRESS = new a("HAS_ADDED_WORK_ADDRESS", 129, "Has_Added_Work_Address");
    public static final a HAS_ADDED_OTHER_ADDRESS = new a("HAS_ADDED_OTHER_ADDRESS", AppConstants.RESULT_CODE_ORDER_COLLECTED, "Has_Added_Other_Address");
    public static final a HAS_ADDED_STATION = new a("HAS_ADDED_STATION", AppConstants.RESULT_CODE_ORDER_NOT_COLLECTED, "Has_Added_Station");
    public static final a HAS_PHOTO = new a("HAS_PHOTO", AppConstants.RESULT_CODE_FLASH_SALES_SURVEY, "Has_Photo");
    public static final a HAS_SOLD_OUT_ITEM = new a("HAS_SOLD_OUT_ITEM", 133, "Has_Sold_Out_Item");
    public static final a HOME_ADDRESS_AVAILABLE = new a("HOME_ADDRESS_AVAILABLE", 134, "Home_Address_Available");
    public static final a WORK_ADDRESS_AVAILABLE = new a("WORK_ADDRESS_AVAILABLE", 135, "Work_Address_Available");
    public static final a OTHER_ADDRESS_AVAILABLE = new a("OTHER_ADDRESS_AVAILABLE", 136, "Other_Address_Available");
    public static final a HORIZONTAL_POSITION = new a("HORIZONTAL_POSITION", 137, "Horizontal_Position");
    public static final a HOST = new a("HOST", 138, "Host");
    public static final a HOW_MUCH_SPENT = new a("HOW_MUCH_SPENT", 139, "How_Much_Spent");
    public static final a ID = new a("ID", 140, "Id");
    public static final a IMPORTANT_UPDATES = new a("IMPORTANT_UPDATES", 141, "Important_Updates");
    public static final a INGREDIENT_NAME = new a("INGREDIENT_NAME", 142, "Ingredient_Name");
    public static final a INVALID_LOCAL = new a("INVALID_LOCAL", 143, "Invalid_Local");
    public static final a INVALID_SERVER = new a("INVALID_SERVER", 144, "Invalid_Server");
    public static final a IS_ADDRESS_OUTSIDE_DELIVERY_AREA = new a("IS_ADDRESS_OUTSIDE_DELIVERY_AREA", 145, "Is_Address_Outside_Delivery_Area");
    public static final a IS_DEFAULT_PAYMENT_METHOD = new a("IS_DEFAULT_PAYMENT_METHOD", 146, "Is_Default_Payment_Method");
    public static final a IS_DONATION = new a("IS_DONATION", 147, "Is_Donation");
    public static final a IS_EMPTY = new a("IS_EMPTY", AppConstants.CONTACT_US_REQUEST_FILE, "Is_Empty");
    public static final a IS_FAVORITE = new a("IS_FAVORITE", 149, "Is_Favorite");
    public static final a IS_FREE_DELIVERY_ACHIEVED = new a("IS_FREE_DELIVERY_ACHIEVED", 150, "Is_Free_Delivery_Achieved");
    public static final a IS_MOV_ACHIEVED = new a("IS_MOV_ACHIEVED", 151, "Is_MOV_Achieved");
    public static final a IS_NEW_VOUCHER_USED = new a("IS_NEW_VOUCHER_USED", 152, "Is_New_Voucher_Used");
    public static final a IS_PRIMARY_CHARITY_COLLECTOR = new a("IS_PRIMARY_CHARITY_COLLECTOR", 153, "Is_Primary_Charity_Collector");
    public static final a IS_SAVED_PAYMENT_METHOD = new a("IS_SAVED_PAYMENT_METHOD", 154, "Is_Saved_Payment_Method");
    public static final a IS_AES = new a("IS_AES", 155, "Is_Aes");
    public static final a IS_REMINDER_SET = new a("IS_REMINDER_SET", 156, "Is_Reminder_Set");
    public static final a IS_LOCAL_HERO = new a("IS_LOCAL_HERO", 157, "Is_Local_Hero");
    public static final a ITEM_CATEGORY = new a("ITEM_CATEGORY", 158, "Item_Category");
    public static final a ITEMS_COUNT = new a("ITEMS_COUNT", 159, "Items_Count");
    public static final a ITEMS_COUNT_WITH_REMINDER_SET = new a("ITEMS_COUNT_WITH_REMINDER_SET", 160, "Items_Count_With_Reminder_Set");
    public static final a ITEM_ID = new a("ITEM_ID", 161, "Item_Id");
    public static final a ITEMS = new a("ITEMS", 162, "Items");
    public static final a ITEM_TYPE = new a("ITEM_TYPE", 163, "Item_Type");
    public static final a ITEM_TAGS = new a("ITEM_TAGS", 164, "Item_Tags");
    public static final a KNOW_TYPE = new a("KNOW_TYPE", 165, "Know_Type");
    public static final a LAPSED_REACTIVATION_PURCHASE = new a("LAPSED_REACTIVATION_PURCHASE", 166, "Lapsed_Reactivation_Purchase");
    public static final a LOGIN = new a("LOGIN", 167, "Login");
    public static final a LOGIN_PUSH_NOTIFICATIONS = new a("LOGIN_PUSH_NOTIFICATIONS", 168, "Login_Push_Notifications");
    public static final a LOGIN_SMS_NOTIFICATIONS = new a("LOGIN_SMS_NOTIFICATIONS", 169, "Login_SMS_Notifications");
    public static final a LOYALTY_CARD_STAMPS = new a("LOYALTY_CARD_STAMPS", 170, "Loyalty_Card_Stamps");
    public static final a LOYALTY_CARD_STATE = new a("LOYALTY_CARD_STATE", 171, "Loyalty_Card_State");
    public static final a MANUFACTURERS_ITEM = new a("MANUFACTURERS_ITEM", 172, "Manufacturers_Item");
    public static final a MARKETING = new a("MARKETING", 173, "Marketing");
    public static final a MESSAGE = new a("MESSAGE", 174, "Message");
    public static final a METHOD = new a("METHOD", 175, "Method");
    public static final a MINUTES_LEFT_TO_COLLECT = new a("MINUTES_LEFT_TO_COLLECT", 176, "MinutesLeftToCollect");
    public static final a MINUTES_TO_COLLECT_WHEN_LISTED = new a("MINUTES_TO_COLLECT_WHEN_LISTED", 177, "MinutesToCollectWhenListed");
    public static final a MIGRATION_SUCCESS = new a("MIGRATION_SUCCESS", 178, "Migration_Success");
    public static final a MOV_THRESHOLD = new a("MOV_THRESHOLD", 179, "MOV_Threshold");
    public static final a NAME = new a("NAME", 180, "Name");
    public static final a NO_DEFAULT_OR_SAVED_PAYMENT_METHOD = new a("NO_DEFAULT_OR_SAVED_PAYMENT_METHOD", 181, "No_Default_Or_Saved_Payment_Method");
    public static final a NOTIFICATION_ENABLED = new a("NOTIFICATION_ENABLED", 182, "Notification_Enabled");
    public static final a NPS_STEP = new a("NPS_STEP", 183, "Step");
    public static final a NUMBER_OF_CONFLICTS = new a("NUMBER_OF_CONFLICTS", 184, "Number_Of_Conflicts");
    public static final a NUMBER_OF_KEPT_CONFLICTS = new a("NUMBER_OF_KEPT_CONFLICTS", ModuleDescriptor.MODULE_VERSION, "Number_Of_Kept_Conflicts");
    public static final a OPENED_FROM = new a("OPENED_FROM", 186, "Opened_From");
    public static final a OPENED_FROM_DEEPLINK = new a("OPENED_FROM_DEEPLINK", 187, "Opened_From_Deeplink");
    public static final a OPENED_FROM_SCREEN_NAME = new a("OPENED_FROM_SCREEN_NAME", 188, "Opened_From_Screen_Name");
    public static final a OPT_IN = new a("OPT_IN", 189, "Opt_In");
    public static final a ORDER_CHANGED_COUNT = new a("ORDER_CHANGED_COUNT", 190, "Order_Changed_Count");
    public static final a ORDER_ID = new a("ORDER_ID", 191, "Order_Id");
    public static final a OVERALL = new a("OVERALL", BERTags.PRIVATE, "Overall");
    public static final a OVERALL_RATING = new a("OVERALL_RATING", 193, "Overall_Rating");
    public static final a PACKAGING_TYPE = new a("PACKAGING_TYPE", 194, "Packaging_Type");
    public static final a PAYMENT_METHOD = new a("PAYMENT_METHOD", 195, "Payment_Method");
    public static final a PAYMENT_PROVIDER = new a("PAYMENT_PROVIDER", 196, "Payment_Provider");
    public static final a PAYMENT_STATE = new a("PAYMENT_STATE", 197, "Payment_State");
    public static final a PAYMENT_TYPES = new a("PAYMENT_TYPES", 198, "Payment_Types");
    public static final a PHOTO_COUNT = new a("PHOTO_COUNT", 199, "Photo_Count");
    public static final a PICKUP_WINDOW_START_SECOND = new a("PICKUP_WINDOW_START_SECOND", 200, "Pickup_Window_Start_Second");
    public static final a PICTURE_UPLOADED = new a("PICTURE_UPLOADED", AppConstants.PERMISSIONS_REQUEST_USE_LOCATION, "Picture_Uploaded");
    public static final a PLACEMENT = new a("PLACEMENT", AppConstants.PERMISSIONS_REQUEST_CALL_PHONE, "Placement");
    public static final a PREFILLED = new a("PREFILLED", 203, "Prefilled");
    public static final a PREFERENCES = new a("PREFERENCES", 204, "Preferences");
    public static final a PRESELECTED_METHOD = new a("PRESELECTED_METHOD", 205, "Preselected_Method");
    public static final a PRICE = new a("PRICE", 206, "Price");
    public static final a PROBABILITY = new a("PROBABILITY", 207, "Probability");
    public static final a PUSH_DAILY_REMINDER_DAY_COUNT = new a("PUSH_DAILY_REMINDER_DAY_COUNT", 208, "Push_Daily_Reminder_Day_Count");
    public static final a PUSH_DAILY_REMINDER_STATUS = new a("PUSH_DAILY_REMINDER_STATUS", 209, "Push_Daily_Reminder_Status");
    public static final a PUSH_IMPORTANT_UPDATES_STATUS = new a("PUSH_IMPORTANT_UPDATES_STATUS", 210, "Push_Important_Updates_Status");
    public static final a PUSH_MARKETING_STATUS = new a("PUSH_MARKETING_STATUS", Primes.SMALL_FACTOR_LIMIT, "Push_Marketing_Status");
    public static final a PUSH_BAG_ALERTS_STATUS = new a("PUSH_BAG_ALERTS_STATUS", 212, "Push_Bag_Alerts_Status");
    public static final a PUSH_OPTIN_STATUS = new a("PUSH_OPTIN_STATUS", 213, "Push_Optin_Status");
    public static final a QUALITY_REASON = new a("QUALITY_REASON", 214, "Quality_Reason");
    public static final a QUANTITY = new a("QUANTITY", 215, "Quantity");
    public static final a QUANTITY_REASON = new a("QUANTITY_REASON", 216, "Quantity_Reason");
    public static final a RATING_PAGE = new a("RATING_PAGE", 217, "Rating_Page");
    public static final a RATING_DESCRIBED = new a("RATING_DESCRIBED", 218, "Rating_Described");
    public static final a RATING_VERSION = new a("RATING_VERSION", 219, "Rating_Version");
    public static final a RECOMMENDED_ITEM_ID = new a("RECOMMENDED_ITEM_ID", 220, "Recommended_Item_Id");
    public static final a REASON = new a("REASON", 221, "Reason");
    public static final a REDEEMED = new a("REDEEMED", AppConstants.GPS_SETTINGS, "Redeemed");
    public static final a RECIPE_COUNT = new a("RECIPE_COUNT", AppConstants.GO_TO_GPS_SETTINGS, "Recipe_Count");
    public static final a REMINDER_TYPE = new a("REMINDER_TYPE", BERTags.FLAGS, "Reminder_Type");
    public static final a REVENUE = new a("REVENUE", 225, "revenue");
    public static final a SCROLL_TO_RESERVE = new a("SCROLL_TO_RESERVE", 226, "Scroll_To_Reserve");
    public static final a STCB_RECOMMENDED_ITEM_ID = new a("STCB_RECOMMENDED_ITEM_ID", 227, "STCB_Recommended_Item_Id");
    public static final a SCREEN = new a("SCREEN", 228, "Screen");
    public static final a SCREEN_NAME = new a("SCREEN_NAME", 229, "Screen_Name");
    public static final a SHOWN_METHOD = new a("SHOWN_METHOD", 230, "Shown_Method");
    public static final a SECTIONS_VIEWED = new a("SECTIONS_VIEWED", 231, "Sections_Viewed");
    public static final a SELECTED = new a("SELECTED", 232, ChipSemanticsKt.CHIP_STATE_DESCRIPTION_SELECTED);
    public static final a SELECTED_CATEGORY = new a("SELECTED_CATEGORY", 233, "Selected_Category");
    public static final a SELECTED_DIET_TYPE = new a("SELECTED_DIET_TYPE", 234, "Selected_DietType");
    public static final a SELECTED_FILTERS = new a("SELECTED_FILTERS", 235, "Selected_Filters");
    public static final a SELECTED_METHOD = new a("SELECTED_METHOD", 236, "Selected_Method");
    public static final a SELECTED_VALUES = new a("SELECTED_VALUES", 237, "Selected_Values");
    public static final a SELECTED_LOCATION = new a("SELECTED_LOCATION", 238, "Selected_Location");
    public static final a SEEN = new a("SEEN", 239, "Seen");
    public static final a SERVICE = new a("SERVICE", 240, "Service");
    public static final a SERVICE_REASON = new a("SERVICE_REASON", 241, "Service_Reason");
    public static final a SEARCH_TYPE = new a("SEARCH_TYPE", 242, "Search_Type");
    public static final a SEARCH_CONTEXT = new a("SEARCH_CONTEXT", 243, "Search_Context");
    public static final a SESSION_ID = new a("SESSION_ID", 244, "Session_Id");
    public static final a SETTINGS = new a("SETTINGS", 245, "Settings");
    public static final a SHIPPING_METHOD = new a("SHIPPING_METHOD", 246, "Shipping_Method");
    public static final a SHOPPED_HERE_BEFORE = new a("SHOPPED_HERE_BEFORE", 247, "Shopped_Here_Before");
    public static final a SOLD_OUT_ITEM_COUNT = new a("SOLD_OUT_ITEM_COUNT", 248, "Sold_Out_Item_Count");
    public static final a SORTED_BY = new a("SORTED_BY", 249, "Sorted_By");
    public static final a SOURCE = new a("SOURCE", m0.DEFAULT_SWIPE_ANIMATION_DURATION, "Source");
    public static final a STATE = new a("STATE", 251, "State");
    public static final a STATIONS_AVAILABLE = new a("STATIONS_AVAILABLE", 252, "Stations_Available");
    public static final a STATUS_CODE = new a("STATUS_CODE", 253, "Status_Code");
    public static final a STORE_ID = new a("STORE_ID", 254, "Store_Id");
    public static final a STORE_NAME = new a("STORE_NAME", 255, "Store_Name");
    public static final a SWIPE_ACTIVE = new a("SWIPE_ACTIVE", 256, "Swipe_Active");
    public static final a SWITCH_TO_STATE = new a("SWITCH_TO_STATE", 257, "Switch_To_State");
    public static final a TAB = new a("TAB", 258, "Tab");
    public static final a TAGS = new a("TAGS", 259, "Tags");
    public static final a THREE_DS_ERROR_MESSAGE = new a("THREE_DS_ERROR_MESSAGE", 260, "3DS_Error_Message");
    public static final a TITLE = new a("TITLE", 261, "Title");
    public static final a TOPIC = new a("TOPIC", 262, "Topic");
    public static final a TOTAL_PRICE = new a("TOTAL_PRICE", 263, "Total_Price");
    public static final a TOTAL_QUANTITY = new a("TOTAL_QUANTITY", 264, "Total_Quantity");
    public static final a TRANSLATION_AVAILABLE = new a("TRANSLATION_AVAILABLE", 265, "Translation_Available");
    public static final a TRANSLATION_ENABLED = new a("TRANSLATION_ENABLED", 266, "Translation_Enabled");
    public static final a TURN_REMINDER = new a("TURN_REMINDER", 267, "Turn_Reminder");
    public static final a TYPE = new a(CredentialProviderBaseController.TYPE_TAG, 268, "Type");
    public static final a UNAVAILABLE_CUSTOM_DAYS = new a("UNAVAILABLE_CUSTOM_DAYS", 269, "Unavailable_custom_days");
    public static final a UNAVAILABLE_DAYS_TO_COLLECT = new a("UNAVAILABLE_DAYS_TO_COLLECT", 270, "Unavailable_Days_To_Collect");
    public static final a UNFOLDED = new a("UNFOLDED", 271, "Unfolded");
    public static final a USER_COUNTRY = new a("USER_COUNTRY", 272, "User_Country");
    public static final a USER_LANGUAGE = new a("USER_LANGUAGE", 273, "User_Language");
    public static final a USER_MEAL_DISTANCE_METERS = new a("USER_MEAL_DISTANCE_METERS", 274, "UserMealDistanceMeters");
    public static final a USER_TYPE = new a("USER_TYPE", 275, "User_Type");
    public static final a VARIETY_REASON = new a("VARIETY_REASON", 276, "Variety_Reason");
    public static final a VERIFICATION_METHOD = new a("VERIFICATION_METHOD", 277, "Verification_Method");
    public static final a VERIFY_SHOWN_BANNER = new a("VERIFY_SHOWN_BANNER", 278, "Verify_Banner_Shown");
    public static final a VERSION = new a("VERSION", 279, "Version");
    public static final a VERTICAL_POSITION = new a("VERTICAL_POSITION", 280, "Vertical_Position");
    public static final a VOUCHER_CODE = new a("VOUCHER_CODE", 281, "Voucher_Code");
    public static final a WARNING = new a("WARNING", 282, "Warning");
    public static final a WEEK_NUMBER = new a("WEEK_NUMBER", 283, "Week_Number");
    public static final a WENT_FOR_SURPRISE_BAG = new a("WENT_FOR_SURPRISE_BAG", 284, "Went_For_Surprise_Bag");
    public static final a WHY_THIS_BAG = new a("WHY_THIS_BAG", 285, "Why_This_Bag");
    public static final a WHY_EMPTY = new a("WHY_EMPTY", 286, "Why_Empty");
    public static final a WOULD_BUY_AGAIN = new a("WOULD_BUY_AGAIN", 287, "Would_Buy_Again");
    public static final a GENERIC_SCREEN_NAME = new a("GENERIC_SCREEN_NAME", 288, "screen_name");
    public static final a GENERIC_ELEMENT_NAME = new a("GENERIC_ELEMENT_NAME", 289, "element_name");
    public static final a GENERIC_ACTION_TYPE = new a("GENERIC_ACTION_TYPE", 290, "action_type");
    public static final a GENERIC_PLATFORM = new a("GENERIC_PLATFORM", 291, "platform");
    public static final a GENERIC_MODULE_NAME = new a("GENERIC_MODULE_NAME", 292, "module_name");
    public static final a GENERIC_ITEM_ID = new a("GENERIC_ITEM_ID", 293, "item_id");
    public static final a GENERIC_ITEM_TYPE = new a("GENERIC_ITEM_TYPE", 294, "item_type");
    public static final a GENERIC_ITEM_CATEGORY = new a("GENERIC_ITEM_CATEGORY", 295, "item_category");
    public static final a GENERIC_STORE_RATING = new a("GENERIC_STORE_RATING", 296, "store_rating");
    public static final a GENERIC_STORE_NAME = new a("GENERIC_STORE_NAME", 297, "store_name");
    public static final a GENERIC_INTERACTION_STATUS = new a("GENERIC_INTERACTION_STATUS", 298, "interaction_status");
    public static final a GENERIC_INDEX = new a("GENERIC_INDEX", 299, "index");
    public static final a GENERIC_TOTAL_RESULTS_COUNT = new a("GENERIC_TOTAL_RESULTS_COUNT", 300, "total_results_count");

    static {
        a[] aVarArrA = a();
        $VALUES = aVarArrA;
        $ENTRIES = n.w(aVarArrA);
    }

    public a(String str, int i11, String str2) {
        this.value = str2;
    }

    public static final /* synthetic */ a[] a() {
        return new a[]{ACTION, AUTO_SCROLLED_TO, ACTION_TYPE, ADDRESS_PREFILLED, AF_QUANTITY, AF_CONTENT_TYPE, AF_CURRENCY, AF_ORDER_ID, AF_REVENUE, ANSWER, ANSWERS, APP_STORE, ATTACHMENT, AVAILABLE_BACKUP_DONATIONS, AVAILABLE_CUSTOM_DAYS, AVAILABLE_DAYS_TO_COLLECT, AVAILABLE_ITEM_COUNT, AVAILABLE_ON_MONDAY, AVAILABLE_ON_TUESDAY, AVAILABLE_ON_WEDNESDAY, AVAILABLE_ON_THURSDAY, AVAILABLE_ON_FRIDAY, AVAILABLE_ON_SATURDAY, AVAILABLE_ON_SUNDAY, AVAILABLE_PLANNED_DONATIONS, AVAILABLE_PRIMARY_DONATIONS, AVAILABLE_STOCK, AVAILABLE_FILTERS, AVAILABLE_ITEMS, BAG_ALERTS, BANNER_TYPE, BASKET_ID, BOUGHT_ANYTHING_ELSE, BRACKET, BRAZE_EXTERNAL_USER_ID, BUCKET, BUCKETS_SHOWN, C2B_REFERRAL_CARD_SHOWN, CALENDAR_OPTIN_STATUS, CANCELLING_ENTITY, CAMERA_PHOTO_COUNT, CATEGORY, CHARITY_IS_AVAILABLE, CHARITY_COUNTRY, CHARITY_LOGIN_SECTION, CHANGE_AVAILABLE, CHECKOUT_ERROR_CAUSE, CHURNED_REACTIVATION_PURCHASE, CLICKED, CLICK_FROM, COLLECTION_TYPE, CONTENT_DESCRIBED, CORRELATION_ID, COUNT_SPECIAL_REWARDS, COUNT_TAGS_SEEN, COUNT_INITIAL_TAGS_VISIBLE, CREATED_AT, CURRENCY, CURRENT_DISTANCE_KM_CHOSEN, CURRENT_STATE, CUSTOM_DAYS_CLOSED_FROM, DAILY_REMINDER, DAY, DAY_PLANNED_DONATIONS, DAYS_SINCE_LAST_PURCHASE, DIRECTIONS, DISCOUNT_OR_VOUCHER_AVAILABLE, DISCOUNT_USED, DONATION_CANCELLED, DONATION_COLLECTION_INSTRUCTIONS, DONATION_COLLECTION_START_TIME, DONATION_COLLECTION_TIME_UPDATED, DONATION_FOOD_CATEGORIES, DONATION_INVENTORY_UPDATES, DONATION_NUMBER_OF_ITEMS, DONATION_UPDATED_STATUS, DONATION_WINDOW_LENGTH, DONATIONS_CANCELLATIONS, DONATIONS_COLLECTION_TIME_UPDATES, DONATIONS_INVENTORY_UPDATES, DEEPLINK_CAMPAIGN_ID, DEEPLINK_SOURCE, DEEPLINK_TYPE, DELIVERY_AVAILABLE, DELIVERY_HAS_STOCK, DISCOVER, DISCOVER_BUCKET, DISTANCE_KM, DYNAMIC_ITEM, EMAIL_OPTIN_STATUS, ERROR_TYPE, EXCEPTION, EXISTS, EXPECTED_DATE_COLLECTION, EXPECTED_ENDING_TIME_COLLECTION, EXPECTED_STARTING_TIME_COLLECTION, EXPLORE_WEEK_AFTER, EXPLORE_WEEK_BEFORE, FB_ITEM_ID, FB_ITEM_NAME, FB_ITEM_CATEGORY, FB_PRICE, FB_QUANTITY, FB_AFFILIATION, FB_TRANSACTION_ID, FB_VALUE, FB_CURRENCY, FB_ITEMS, FIRST_PURCHASE, FOOD_QUALITY, FOOD_VARIETY, FREE_DELIVERY_THRESHOLD, FREE_TEXT_ANSWER, FOOD_QUANTITY, FUTURE_ITEM, GENERAL_INFO, GPS_ENABLED, GALLERY_PHOTO_COUNT, HAS_DEFAULT_PAYMENT_METHOD, HAS_PURCHASE_LIMIT, HAS_RESERVATION, HAS_SEARCH, HAS_SPECIAL_OFFERS, HAS_STOCK, HAS_SUGGESTION, HAS_TIME_FILTER, HERO_COMPONENT, HIDE_SOLD_OUT, HAS_ADDED_HOME_ADDRESS, HAS_ADDED_WORK_ADDRESS, HAS_ADDED_OTHER_ADDRESS, HAS_ADDED_STATION, HAS_PHOTO, HAS_SOLD_OUT_ITEM, HOME_ADDRESS_AVAILABLE, WORK_ADDRESS_AVAILABLE, OTHER_ADDRESS_AVAILABLE, HORIZONTAL_POSITION, HOST, HOW_MUCH_SPENT, ID, IMPORTANT_UPDATES, INGREDIENT_NAME, INVALID_LOCAL, INVALID_SERVER, IS_ADDRESS_OUTSIDE_DELIVERY_AREA, IS_DEFAULT_PAYMENT_METHOD, IS_DONATION, IS_EMPTY, IS_FAVORITE, IS_FREE_DELIVERY_ACHIEVED, IS_MOV_ACHIEVED, IS_NEW_VOUCHER_USED, IS_PRIMARY_CHARITY_COLLECTOR, IS_SAVED_PAYMENT_METHOD, IS_AES, IS_REMINDER_SET, IS_LOCAL_HERO, ITEM_CATEGORY, ITEMS_COUNT, ITEMS_COUNT_WITH_REMINDER_SET, ITEM_ID, ITEMS, ITEM_TYPE, ITEM_TAGS, KNOW_TYPE, LAPSED_REACTIVATION_PURCHASE, LOGIN, LOGIN_PUSH_NOTIFICATIONS, LOGIN_SMS_NOTIFICATIONS, LOYALTY_CARD_STAMPS, LOYALTY_CARD_STATE, MANUFACTURERS_ITEM, MARKETING, MESSAGE, METHOD, MINUTES_LEFT_TO_COLLECT, MINUTES_TO_COLLECT_WHEN_LISTED, MIGRATION_SUCCESS, MOV_THRESHOLD, NAME, NO_DEFAULT_OR_SAVED_PAYMENT_METHOD, NOTIFICATION_ENABLED, NPS_STEP, NUMBER_OF_CONFLICTS, NUMBER_OF_KEPT_CONFLICTS, OPENED_FROM, OPENED_FROM_DEEPLINK, OPENED_FROM_SCREEN_NAME, OPT_IN, ORDER_CHANGED_COUNT, ORDER_ID, OVERALL, OVERALL_RATING, PACKAGING_TYPE, PAYMENT_METHOD, PAYMENT_PROVIDER, PAYMENT_STATE, PAYMENT_TYPES, PHOTO_COUNT, PICKUP_WINDOW_START_SECOND, PICTURE_UPLOADED, PLACEMENT, PREFILLED, PREFERENCES, PRESELECTED_METHOD, PRICE, PROBABILITY, PUSH_DAILY_REMINDER_DAY_COUNT, PUSH_DAILY_REMINDER_STATUS, PUSH_IMPORTANT_UPDATES_STATUS, PUSH_MARKETING_STATUS, PUSH_BAG_ALERTS_STATUS, PUSH_OPTIN_STATUS, QUALITY_REASON, QUANTITY, QUANTITY_REASON, RATING_PAGE, RATING_DESCRIBED, RATING_VERSION, RECOMMENDED_ITEM_ID, REASON, REDEEMED, RECIPE_COUNT, REMINDER_TYPE, REVENUE, SCROLL_TO_RESERVE, STCB_RECOMMENDED_ITEM_ID, SCREEN, SCREEN_NAME, SHOWN_METHOD, SECTIONS_VIEWED, SELECTED, SELECTED_CATEGORY, SELECTED_DIET_TYPE, SELECTED_FILTERS, SELECTED_METHOD, SELECTED_VALUES, SELECTED_LOCATION, SEEN, SERVICE, SERVICE_REASON, SEARCH_TYPE, SEARCH_CONTEXT, SESSION_ID, SETTINGS, SHIPPING_METHOD, SHOPPED_HERE_BEFORE, SOLD_OUT_ITEM_COUNT, SORTED_BY, SOURCE, STATE, STATIONS_AVAILABLE, STATUS_CODE, STORE_ID, STORE_NAME, SWIPE_ACTIVE, SWITCH_TO_STATE, TAB, TAGS, THREE_DS_ERROR_MESSAGE, TITLE, TOPIC, TOTAL_PRICE, TOTAL_QUANTITY, TRANSLATION_AVAILABLE, TRANSLATION_ENABLED, TURN_REMINDER, TYPE, UNAVAILABLE_CUSTOM_DAYS, UNAVAILABLE_DAYS_TO_COLLECT, UNFOLDED, USER_COUNTRY, USER_LANGUAGE, USER_MEAL_DISTANCE_METERS, USER_TYPE, VARIETY_REASON, VERIFICATION_METHOD, VERIFY_SHOWN_BANNER, VERSION, VERTICAL_POSITION, VOUCHER_CODE, WARNING, WEEK_NUMBER, WENT_FOR_SURPRISE_BAG, WHY_THIS_BAG, WHY_EMPTY, WOULD_BUY_AGAIN, GENERIC_SCREEN_NAME, GENERIC_ELEMENT_NAME, GENERIC_ACTION_TYPE, GENERIC_PLATFORM, GENERIC_MODULE_NAME, GENERIC_ITEM_ID, GENERIC_ITEM_TYPE, GENERIC_ITEM_CATEGORY, GENERIC_STORE_RATING, GENERIC_STORE_NAME, GENERIC_INTERACTION_STATUS, GENERIC_INDEX, GENERIC_TOTAL_RESULTS_COUNT};
    }

    public static a valueOf(String str) {
        return (a) Enum.valueOf(a.class, str);
    }

    public static a[] values() {
        return (a[]) $VALUES.clone();
    }

    public final String c() {
        return this.value;
    }
}
