package dv;

import com.adyen.checkout.googlepay.AllowedCardNetworks;
import com.app.tgtg.model.local.AppConstants;
import com.braze.configuration.BrazeConfigurationProvider;
import com.tgtg.componentlibrary.component.chip.model.ChipSemanticsKt;
import com.tgtg.componentlibrary.component.pageheader.PantryPageHeaderKt;
import org.jetbrains.annotations.NotNull;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* JADX INFO: compiled from: r8-map-id-bad8e3e1b75e2d3fd72c92f1b960553adb24fef824cc9e98cee450b85845d4c2 */
/* JADX INFO: loaded from: classes2.dex */
public final class d {
    private static final /* synthetic */ a80.a $ENTRIES;
    private static final /* synthetic */ d[] $VALUES;
    public static final d ADDED;
    public static final d AFTER_RATING_BUTTON;
    public static final d BACK;
    public static final d BAG_FEE;
    public static final d BAG_FEE_MANDATED;
    public static final d BASKET_RECOMMENDATION;
    public static final d BLOCKED;
    public static final d BROWSE;
    public static final d BROWSE_AVAILABLE_ITEMS_ELEVEN_PLUS;
    public static final d BROWSE_AVAILABLE_ITEMS_ONE_TO_TEN;
    public static final d BROWSE_AVAILABLE_ITEMS_ZERO;
    public static final d CALENDAR_ALERTS;
    public static final d CARD;
    public static final d CAREERS;
    public static final d CATERING;
    public static final d CELEBRATION_SCREEN;
    public static final d CHARITY_COUNTRY;
    public static final d CLAIMED;
    public static final d CLICK;
    public static final d COMPLEX_FILTER_CATEGORY;
    public static final d COMPLEX_FILTER_COLLECTION_TIME;
    public static final d COMPLEX_FILTER_COLLECT_NOW;
    public static final d COMPLEX_FILTER_DIET;
    public static final d COMPLEX_FILTER_FLAG_TRUE;
    public static final d COMPLEX_FILTER_SOLD_OUT;
    public static final d COMPLEX_FILTER_SORT;
    public static final d CONTAINER_REQUIRED;
    public static final d CONTENT_DESCRIBED;
    public static final d CROSS;
    public static final d CURRENT_LOCATION;
    public static final d DEEP_LINK;
    public static final d DELIVERY_FEE;
    public static final d DISCOVER;
    public static final d DISCOVER_BUCKET;
    public static final d DISCOVER_CARD;
    public static final d DISCOVER_PAGE;
    public static final d DISMISSED;
    public static final d DISMISS_CARD;
    public static final d EMPTY_SAVED_RECIPE_LIST;
    public static final d EVEN;
    public static final d EVERYTHING;
    public static final d EXPIRED;
    public static final d FALSE;
    public static final d FAVORITES_CAROUSEL;
    public static final d FAVORITES_PAGE;
    public static final d FAVORITES_SCREEN;
    public static final d FAVORITE_BUCKET;
    public static final d FAVORITE_HEART;
    public static final d FAVOURITES;
    public static final d FAVOURITES_CAROUSEL_BUTTON;
    public static final d FUTURE_ITEM;
    public static final d GENERAL;
    public static final d GOT_IT_BUTTON;
    public static final d HERO_COMPONENT;
    public static final d HOME;
    public static final d HOW_MUCH_SPENT;
    public static final d INFO_BUTTON;
    public static final d INGREDIENTS;
    public static final d INSTRUCTIONS;
    public static final d INVITATION_ACCEPTED;
    public static final d INVITE_FRIENDS;
    public static final d ITEM;
    public static final d ITEM_CARD;
    public static final d ITEM_PAGE_BANNER;
    public static final d ITEM_PAGE_BELL;
    public static final d ITEM_VIEW;
    public static final d LEARN_MORE_BUTTON;
    public static final d LIST;
    public static final d LOGIN;
    public static final d LOGIN_LANDING;
    public static final d MANAGE_ACCOUNT;
    public static final d MANUFACTURER;
    public static final d MANUFACTURER_BUCKET;
    public static final d MANUFACTURE_DISABLE;
    public static final d MAP;
    public static final d MENU;
    public static final d MULTIPLE;
    public static final d MYSTORE_MORE;
    public static final d MYSTORE_SIGNUP;
    public static final d NAVIGATION;
    public static final d NECESSARY;
    public static final d NEW_USER;
    public static final d NO;
    public static final d NONE;
    public static final d NOTIFICATIONS_SETTINGS;
    public static final d NO_RECIPES_FOUND;
    public static final d ODD;
    public static final d OFF;
    public static final d ON;
    public static final d ONBOARDING;
    public static final d ONBOARDING_NATIVE_PROMPT;
    public static final d ONBOARDING_REMINDER;
    public static final d ONE_TIME_REMINDER;
    public static final d OPT_IN;
    public static final d OPT_OUT;
    public static final d ORDER;
    public static final d ORDER_BANNER;
    public static final d ORDER_BLOB;
    public static final d ORDER_CHANGED_POPUP;
    public static final d ORDER_LIST;
    public static final d ORDER_POPUP;
    public static final d ORDER_VIEW;
    public static final d OTHER;
    public static final d PARCEL_DETAILS;
    public static final d PER_BASKET_LIMIT_REACHED;
    public static final d PICTURE_UPLOAD;
    public static final d POST_PURCHASE;
    public static final d PRE_PURCHASE_POPUP;
    public static final d PROFILE;
    public static final d PROVIDE_CHARITY_ID;
    public static final d PROVIDE_EMAIL;
    public static final d RECIPE_GENERATION_LIMIT_REACHED;
    public static final d RECIPE_INTRO_FIRST_STEP;
    public static final d RECIPE_INTRO_SECOND_STEP;
    public static final d RECIPE_INTRO_THIRD_STEP;
    public static final d RECOMMENDATION;
    public static final d RECURRING_REMINDER;
    public static final d REDEEMED;
    public static final d REOPTIN;
    public static final d RETURNING_USER;
    public static final d RETURNING_USER_HAS_SAVED;
    public static final d SAME_TIME_CLOSE_BY;
    public static final d SAVED_RECIPE_LIMIT_REACHED;
    public static final d SCREEN_BASKET;
    public static final d SCREEN_BROWSE_LIST;
    public static final d SCREEN_BROWSE_MAP;
    public static final d SCREEN_CANCELLATION_INFO;
    public static final d SCREEN_DELIVERY;
    public static final d SCREEN_DISCOVER;
    public static final d SCREEN_DISCOVER_BUCKET;
    public static final d SCREEN_FAVORITES;
    public static final d SCREEN_FRIDGE_INTRO;
    public static final d SCREEN_MENU;
    public static final d SCREEN_ORDER;
    public static final d SCREEN_RECIPE;
    public static final d SCREEN_RECIPE_LIST;
    public static final d SCREEN_RECOMMENDATION;
    public static final d SCREEN_SAVED_RECIPES;
    public static final d SCREEN_SAVED_RECIPE_LIST;
    public static final d SCREEN_STORE;
    public static final d SELECTED;
    public static final d SETTINGS;
    public static final d SIGNUP;
    public static final d SINGLE;
    public static final d SKIPPED;
    public static final d SOLD_OUT;
    public static final d SOMETHING_WENT_WRONG;
    public static final d SPLASH;
    public static final d STATIONS;
    public static final d STCB_RECOMMENDATION;
    public static final d STORE;
    public static final d STORE_CANCELLATION;
    public static final d STORE_CANCELLED_POPUP;
    public static final d SURPRISE;
    public static final d TRUE;
    public static final d UNKNOWN;
    public static final d VERIFY_EMAIL;
    public static final d WHY_THIS_BAG;
    public static final d WIDGET;
    public static final d WOB_RECOMMENDATION;
    public static final d WORK;

    @NotNull
    private final String value;

    static {
        d dVar = new d("ADDED", 0, "added");
        ADDED = dVar;
        d dVar2 = new d("AFTER_RATING_BUTTON", 1, "After_Rating_Button");
        AFTER_RATING_BUTTON = dVar2;
        d dVar3 = new d("BACK", 2, PantryPageHeaderKt.BACK_CONTENT_DESCRIPTION);
        BACK = dVar3;
        d dVar4 = new d("BAG_FEE", 3, "Bag_Fee");
        BAG_FEE = dVar4;
        d dVar5 = new d("BAG_FEE_MANDATED", 4, "Bag_Fee_Mandated");
        BAG_FEE_MANDATED = dVar5;
        d dVar6 = new d("BASKET_RECOMMENDATION", 5, "Basket_Recommendation");
        BASKET_RECOMMENDATION = dVar6;
        d dVar7 = new d("BLOCKED", 6, "BLOCKED");
        BLOCKED = dVar7;
        d dVar8 = new d("BROWSE", 7, "Browse");
        BROWSE = dVar8;
        d dVar9 = new d("BROWSE_AVAILABLE_ITEMS_ELEVEN_PLUS", 8, "11plus");
        BROWSE_AVAILABLE_ITEMS_ELEVEN_PLUS = dVar9;
        d dVar10 = new d("BROWSE_AVAILABLE_ITEMS_ONE_TO_TEN", 9, "1-10");
        BROWSE_AVAILABLE_ITEMS_ONE_TO_TEN = dVar10;
        d dVar11 = new d("BROWSE_AVAILABLE_ITEMS_ZERO", 10, "Zero");
        BROWSE_AVAILABLE_ITEMS_ZERO = dVar11;
        d dVar12 = new d("CALENDAR_ALERTS", 11, "Calendar_Alerts");
        CALENDAR_ALERTS = dVar12;
        d dVar13 = new d("CARD", 12, "card");
        CARD = dVar13;
        d dVar14 = new d("CATERING", 13, "CATERING");
        CATERING = dVar14;
        d dVar15 = new d("CAREERS", 14, "Careers");
        CAREERS = dVar15;
        d dVar16 = new d("CELEBRATION_SCREEN", 15, "Celebration_Screen");
        CELEBRATION_SCREEN = dVar16;
        d dVar17 = new d("CHARITY_COUNTRY", 16, "Charity_Country");
        CHARITY_COUNTRY = dVar17;
        d dVar18 = new d("CLAIMED", 17, "Claimed");
        CLAIMED = dVar18;
        d dVar19 = new d("CLICK", 18, "click");
        CLICK = dVar19;
        d dVar20 = new d("COMPLEX_FILTER_CATEGORY", 19, "Category");
        COMPLEX_FILTER_CATEGORY = dVar20;
        d dVar21 = new d("COMPLEX_FILTER_COLLECTION_TIME", 20, "Collection_Time");
        COMPLEX_FILTER_COLLECTION_TIME = dVar21;
        d dVar22 = new d("COMPLEX_FILTER_COLLECT_NOW", 21, "Collect_Now");
        COMPLEX_FILTER_COLLECT_NOW = dVar22;
        d dVar23 = new d("COMPLEX_FILTER_DIET", 22, "Diet");
        COMPLEX_FILTER_DIET = dVar23;
        d dVar24 = new d("COMPLEX_FILTER_FLAG_TRUE", 23, "true");
        COMPLEX_FILTER_FLAG_TRUE = dVar24;
        d dVar25 = new d("COMPLEX_FILTER_SOLD_OUT", 24, "Sold_Out");
        COMPLEX_FILTER_SOLD_OUT = dVar25;
        d dVar26 = new d("COMPLEX_FILTER_SORT", 25, "Sort");
        COMPLEX_FILTER_SORT = dVar26;
        d dVar27 = new d("CONTAINER_REQUIRED", 26, "Container_Required");
        CONTAINER_REQUIRED = dVar27;
        d dVar28 = new d("CONTENT_DESCRIBED", 27, "Content_Described");
        CONTENT_DESCRIBED = dVar28;
        d dVar29 = new d("CROSS", 28, "Cross");
        CROSS = dVar29;
        d dVar30 = new d("CURRENT_LOCATION", 29, "Current_Location");
        CURRENT_LOCATION = dVar30;
        d dVar31 = new d("DEEP_LINK", 30, "Deep_Link");
        DEEP_LINK = dVar31;
        d dVar32 = new d("DELIVERY_FEE", 31, "Delivery_Fee");
        DELIVERY_FEE = dVar32;
        d dVar33 = new d(AllowedCardNetworks.DISCOVER, 32, "Discover");
        DISCOVER = dVar33;
        d dVar34 = new d("DISCOVER_BUCKET", 33, "Discover_Bucket");
        DISCOVER_BUCKET = dVar34;
        d dVar35 = new d("DISCOVER_CARD", 34, "Discover_Card");
        DISCOVER_CARD = dVar35;
        d dVar36 = new d("DISCOVER_PAGE", 35, "Discover_Page");
        DISCOVER_PAGE = dVar36;
        d dVar37 = new d("DISMISSED", 36, "Dismissed");
        DISMISSED = dVar37;
        d dVar38 = new d("DISMISS_CARD", 37, "dismiss_card");
        DISMISS_CARD = dVar38;
        d dVar39 = new d("EVEN", 38, "Even");
        EVEN = dVar39;
        d dVar40 = new d("EMPTY_SAVED_RECIPE_LIST", 39, "Empty_Saved_Recipe_List");
        EMPTY_SAVED_RECIPE_LIST = dVar40;
        d dVar41 = new d("EVERYTHING", 40, "Everything");
        EVERYTHING = dVar41;
        d dVar42 = new d("EXPIRED", 41, "Expired");
        EXPIRED = dVar42;
        d dVar43 = new d("FALSE", 42, "False");
        FALSE = dVar43;
        d dVar44 = new d("FAVORITE_BUCKET", 43, "Favorite_Bucket");
        FAVORITE_BUCKET = dVar44;
        d dVar45 = new d("FAVORITE_HEART", 44, "favorite_heart");
        FAVORITE_HEART = dVar45;
        d dVar46 = new d("FAVORITES_CAROUSEL", 45, "favorites_carousel");
        FAVORITES_CAROUSEL = dVar46;
        d dVar47 = new d("FAVORITES_PAGE", 46, "Favorites_Page");
        FAVORITES_PAGE = dVar47;
        d dVar48 = new d("FAVORITES_SCREEN", 47, "favorites_screen");
        FAVORITES_SCREEN = dVar48;
        d dVar49 = new d("FAVOURITES", 48, "Favourites");
        FAVOURITES = dVar49;
        d dVar50 = new d("FAVOURITES_CAROUSEL_BUTTON", 49, "Favourites_Carousel_Button");
        FAVOURITES_CAROUSEL_BUTTON = dVar50;
        d dVar51 = new d("FUTURE_ITEM", 50, "Future_Item");
        FUTURE_ITEM = dVar51;
        d dVar52 = new d("GENERAL", 51, BrazeConfigurationProvider.DEFAULT_NOTIFICATION_CHANNEL_NAME_DEFAULT_VALUE);
        GENERAL = dVar52;
        d dVar53 = new d("GOT_IT_BUTTON", 52, "Got_It_Button");
        GOT_IT_BUTTON = dVar53;
        d dVar54 = new d("HERO_COMPONENT", 53, "Hero");
        HERO_COMPONENT = dVar54;
        d dVar55 = new d("HOME", 54, "Home");
        HOME = dVar55;
        d dVar56 = new d("HOW_MUCH_SPENT", 55, "How_Much_Spent");
        HOW_MUCH_SPENT = dVar56;
        d dVar57 = new d("INFO_BUTTON", 56, "Info_Button");
        INFO_BUTTON = dVar57;
        d dVar58 = new d("INGREDIENTS", 57, "Ingredients");
        INGREDIENTS = dVar58;
        d dVar59 = new d("INSTRUCTIONS", 58, "Instructions");
        INSTRUCTIONS = dVar59;
        d dVar60 = new d("INVITATION_ACCEPTED", 59, "Invitation_Accepted");
        INVITATION_ACCEPTED = dVar60;
        d dVar61 = new d("INVITE_FRIENDS", 60, "Invite_Friends");
        INVITE_FRIENDS = dVar61;
        d dVar62 = new d("ITEM", 61, "Item");
        ITEM = dVar62;
        d dVar63 = new d("ITEM_CARD", 62, "Item_Card");
        ITEM_CARD = dVar63;
        d dVar64 = new d("ITEM_PAGE_BANNER", 63, "Item_Page_Banner");
        ITEM_PAGE_BANNER = dVar64;
        d dVar65 = new d("ITEM_PAGE_BELL", 64, "Item_Page_Bell");
        ITEM_PAGE_BELL = dVar65;
        d dVar66 = new d("ITEM_VIEW", 65, "Item_View");
        ITEM_VIEW = dVar66;
        d dVar67 = new d("LEARN_MORE_BUTTON", 66, "Learn_More_Button");
        LEARN_MORE_BUTTON = dVar67;
        d dVar68 = new d("LIST", 67, "List");
        LIST = dVar68;
        d dVar69 = new d("MAP", 68, "Map");
        MAP = dVar69;
        d dVar70 = new d("LOGIN", 69, "Login");
        LOGIN = dVar70;
        d dVar71 = new d("LOGIN_LANDING", 70, "Login_Landing");
        LOGIN_LANDING = dVar71;
        d dVar72 = new d("MANAGE_ACCOUNT", 71, "Manage_Account");
        MANAGE_ACCOUNT = dVar72;
        d dVar73 = new d("MANUFACTURER", 72, "Manufacturer");
        MANUFACTURER = dVar73;
        d dVar74 = new d("MANUFACTURER_BUCKET", 73, "Manufacturer_Bucket");
        MANUFACTURER_BUCKET = dVar74;
        d dVar75 = new d("MANUFACTURE_DISABLE", 74, "Manufacture_Disable");
        MANUFACTURE_DISABLE = dVar75;
        d dVar76 = new d("MENU", 75, "Menu");
        MENU = dVar76;
        d dVar77 = new d("MULTIPLE", 76, "Multiple");
        MULTIPLE = dVar77;
        d dVar78 = new d("MYSTORE_MORE", 77, "MyStore_More");
        MYSTORE_MORE = dVar78;
        d dVar79 = new d("MYSTORE_SIGNUP", 78, "MyStore_Signup");
        MYSTORE_SIGNUP = dVar79;
        d dVar80 = new d("NAVIGATION", 79, "Navigation ");
        NAVIGATION = dVar80;
        d dVar81 = new d("NECESSARY", 80, "Necessary");
        NECESSARY = dVar81;
        d dVar82 = new d("NEW_USER", 81, "New_User");
        NEW_USER = dVar82;
        d dVar83 = new d("NO", 82, "No");
        NO = dVar83;
        d dVar84 = new d("NONE", 83, "None");
        NONE = dVar84;
        d dVar85 = new d("NOTIFICATIONS_SETTINGS", 84, "Notifications_Settings");
        NOTIFICATIONS_SETTINGS = dVar85;
        d dVar86 = new d("NO_RECIPES_FOUND", 85, "No_Recipes_Found");
        NO_RECIPES_FOUND = dVar86;
        d dVar87 = new d("ODD", 86, "Odd");
        ODD = dVar87;
        d dVar88 = new d("OFF", 87, "Off");
        OFF = dVar88;
        d dVar89 = new d("ON", 88, "On");
        ON = dVar89;
        d dVar90 = new d("ONBOARDING", 89, "Onboarding");
        ONBOARDING = dVar90;
        d dVar91 = new d("ONBOARDING_NATIVE_PROMPT", 90, "Onboarding_Native_Prompt");
        ONBOARDING_NATIVE_PROMPT = dVar91;
        d dVar92 = new d("ONBOARDING_REMINDER", 91, "Onboarding_Reminder");
        ONBOARDING_REMINDER = dVar92;
        d dVar93 = new d("ONE_TIME_REMINDER", 92, "One_Time_Reminder");
        ONE_TIME_REMINDER = dVar93;
        d dVar94 = new d("OPT_IN", 93, "Opt_In");
        OPT_IN = dVar94;
        d dVar95 = new d("OPT_OUT", 94, "Opt_Out");
        OPT_OUT = dVar95;
        d dVar96 = new d("ORDER", 95, "Order");
        ORDER = dVar96;
        d dVar97 = new d("ORDER_BANNER", 96, "Order_Banner");
        ORDER_BANNER = dVar97;
        d dVar98 = new d("ORDER_BLOB", 97, "Order_Blob");
        ORDER_BLOB = dVar98;
        d dVar99 = new d("ORDER_CHANGED_POPUP", 98, "Order_Changed_Popup");
        ORDER_CHANGED_POPUP = dVar99;
        d dVar100 = new d("ORDER_LIST", 99, "Order_List");
        ORDER_LIST = dVar100;
        d dVar101 = new d("ORDER_POPUP", 100, "Order_Popup");
        ORDER_POPUP = dVar101;
        d dVar102 = new d("ORDER_VIEW", 101, "Order_View");
        ORDER_VIEW = dVar102;
        d dVar103 = new d("OTHER", 102, "Other");
        OTHER = dVar103;
        d dVar104 = new d("PARCEL_DETAILS", 103, "Parcel_Details");
        PARCEL_DETAILS = dVar104;
        d dVar105 = new d("PER_BASKET_LIMIT_REACHED", 104, "Per_Basket_Limit_Reached");
        PER_BASKET_LIMIT_REACHED = dVar105;
        d dVar106 = new d("PICTURE_UPLOAD", 105, "Picture_Upload");
        PICTURE_UPLOAD = dVar106;
        d dVar107 = new d("POST_PURCHASE", 106, "Post_Purchase");
        POST_PURCHASE = dVar107;
        d dVar108 = new d("PRE_PURCHASE_POPUP", 107, "Pre_Purchase_Popup");
        PRE_PURCHASE_POPUP = dVar108;
        d dVar109 = new d("PROFILE", 108, "Profile");
        PROFILE = dVar109;
        d dVar110 = new d("PROVIDE_CHARITY_ID", 109, "Provide_Charity_Id");
        PROVIDE_CHARITY_ID = dVar110;
        d dVar111 = new d("PROVIDE_EMAIL", 110, "Provide_Email");
        PROVIDE_EMAIL = dVar111;
        d dVar112 = new d("RECOMMENDATION", 111, "Recommendation");
        RECOMMENDATION = dVar112;
        d dVar113 = new d("RECURRING_REMINDER", 112, "Recurring_Reminder");
        RECURRING_REMINDER = dVar113;
        d dVar114 = new d("RETURNING_USER", 113, "Returning_User");
        RETURNING_USER = dVar114;
        d dVar115 = new d("RETURNING_USER_HAS_SAVED", 114, "Returning_User_Has_Saved");
        RETURNING_USER_HAS_SAVED = dVar115;
        d dVar116 = new d("RECIPE_INTRO_FIRST_STEP", 115, "Snap_Photo");
        RECIPE_INTRO_FIRST_STEP = dVar116;
        d dVar117 = new d("RECIPE_INTRO_SECOND_STEP", 116, "Explore_Recipes");
        RECIPE_INTRO_SECOND_STEP = dVar117;
        d dVar118 = new d("RECIPE_INTRO_THIRD_STEP", 117, "Start_Cooking");
        RECIPE_INTRO_THIRD_STEP = dVar118;
        d dVar119 = new d("RECIPE_GENERATION_LIMIT_REACHED", 118, "Recipe_Generation_Limit_Reached");
        RECIPE_GENERATION_LIMIT_REACHED = dVar119;
        d dVar120 = new d("REDEEMED", 119, "Redeemed");
        REDEEMED = dVar120;
        d dVar121 = new d("REOPTIN", 120, "Reoptin");
        REOPTIN = dVar121;
        d dVar122 = new d("SAME_TIME_CLOSE_BY", 121, "SameTimeCloseBy");
        SAME_TIME_CLOSE_BY = dVar122;
        d dVar123 = new d("SAVED_RECIPE_LIMIT_REACHED", 122, "Saved_Recipe_Limit_Reached");
        SAVED_RECIPE_LIMIT_REACHED = dVar123;
        d dVar124 = new d("SCREEN_BASKET", AppConstants.RESULT_CODE_ORDER_CANCELLED, "Screen_Basket");
        SCREEN_BASKET = dVar124;
        d dVar125 = new d("SCREEN_BROWSE_LIST", 124, "Screen_Browse_List");
        SCREEN_BROWSE_LIST = dVar125;
        d dVar126 = new d("SCREEN_BROWSE_MAP", 125, "Screen_Browse_Map");
        SCREEN_BROWSE_MAP = dVar126;
        d dVar127 = new d("SCREEN_CANCELLATION_INFO", 126, "Screen_Cancellation_Info");
        SCREEN_CANCELLATION_INFO = dVar127;
        d dVar128 = new d("SCREEN_DELIVERY", 127, "Screen_Delivery");
        SCREEN_DELIVERY = dVar128;
        d dVar129 = new d("SCREEN_DISCOVER", 128, "Screen_Discover");
        SCREEN_DISCOVER = dVar129;
        d dVar130 = new d("SCREEN_DISCOVER_BUCKET", 129, "Screen_Discover_Bucket");
        SCREEN_DISCOVER_BUCKET = dVar130;
        d dVar131 = new d("SCREEN_FAVORITES", AppConstants.RESULT_CODE_ORDER_COLLECTED, "Screen_Favorites");
        SCREEN_FAVORITES = dVar131;
        d dVar132 = new d("SCREEN_FRIDGE_INTRO", AppConstants.RESULT_CODE_ORDER_NOT_COLLECTED, "Screen_Fridge_Intro");
        SCREEN_FRIDGE_INTRO = dVar132;
        d dVar133 = new d("SCREEN_ORDER", AppConstants.RESULT_CODE_FLASH_SALES_SURVEY, "Screen_Order");
        SCREEN_ORDER = dVar133;
        d dVar134 = new d("SCREEN_RECOMMENDATION", 133, "Screen_Recommendation");
        SCREEN_RECOMMENDATION = dVar134;
        d dVar135 = new d("SCREEN_STORE", 134, "Screen_Store");
        SCREEN_STORE = dVar135;
        d dVar136 = new d("SCREEN_RECIPE_LIST", 135, "Screen_Recipe_List");
        SCREEN_RECIPE_LIST = dVar136;
        d dVar137 = new d("SCREEN_RECIPE", 136, "Screen_Recipe");
        SCREEN_RECIPE = dVar137;
        d dVar138 = new d("SCREEN_SAVED_RECIPES", 137, "Screen_Saved_Recipes");
        SCREEN_SAVED_RECIPES = dVar138;
        d dVar139 = new d("SCREEN_SAVED_RECIPE_LIST", 138, "Screen_Saved_Recipe_List");
        SCREEN_SAVED_RECIPE_LIST = dVar139;
        d dVar140 = new d("SCREEN_MENU", 139, "Screen_Menu");
        SCREEN_MENU = dVar140;
        d dVar141 = new d("SELECTED", 140, ChipSemanticsKt.CHIP_STATE_DESCRIPTION_SELECTED);
        SELECTED = dVar141;
        d dVar142 = new d("SETTINGS", 141, "Settings");
        SETTINGS = dVar142;
        d dVar143 = new d("SIGNUP", 142, "Signup");
        SIGNUP = dVar143;
        d dVar144 = new d("SINGLE", 143, "Single");
        SINGLE = dVar144;
        d dVar145 = new d("SKIPPED", 144, "Skipped");
        SKIPPED = dVar145;
        d dVar146 = new d("SOLD_OUT", 145, "Sold_Out");
        SOLD_OUT = dVar146;
        d dVar147 = new d("SOMETHING_WENT_WRONG", 146, "Something_Went_Wrong");
        SOMETHING_WENT_WRONG = dVar147;
        d dVar148 = new d("SPLASH", 147, "Splash");
        SPLASH = dVar148;
        d dVar149 = new d("STATIONS", AppConstants.CONTACT_US_REQUEST_FILE, "Stations");
        STATIONS = dVar149;
        d dVar150 = new d("STCB_RECOMMENDATION", 149, "STCB_Recommendation");
        STCB_RECOMMENDATION = dVar150;
        d dVar151 = new d("STORE", 150, "Store");
        STORE = dVar151;
        d dVar152 = new d("STORE_CANCELLATION", 151, "Store_Cancellation");
        STORE_CANCELLATION = dVar152;
        d dVar153 = new d("STORE_CANCELLED_POPUP", 152, "Store_Cancelled_Popup");
        STORE_CANCELLED_POPUP = dVar153;
        d dVar154 = new d("SURPRISE", 153, "Surprise");
        SURPRISE = dVar154;
        d dVar155 = new d("TRUE", 154, "True");
        TRUE = dVar155;
        d dVar156 = new d("UNKNOWN", 155, "Unknown");
        UNKNOWN = dVar156;
        d dVar157 = new d("VERIFY_EMAIL", 156, "Verify_Email");
        VERIFY_EMAIL = dVar157;
        d dVar158 = new d("WHY_THIS_BAG", 157, "Why_This_Bag");
        WHY_THIS_BAG = dVar158;
        d dVar159 = new d("WIDGET", 158, "Widget");
        WIDGET = dVar159;
        d dVar160 = new d("WOB_RECOMMENDATION", 159, "WOB_Recommendation");
        WOB_RECOMMENDATION = dVar160;
        d dVar161 = new d("WORK", 160, "Work");
        WORK = dVar161;
        d[] dVarArr = {dVar, dVar2, dVar3, dVar4, dVar5, dVar6, dVar7, dVar8, dVar9, dVar10, dVar11, dVar12, dVar13, dVar14, dVar15, dVar16, dVar17, dVar18, dVar19, dVar20, dVar21, dVar22, dVar23, dVar24, dVar25, dVar26, dVar27, dVar28, dVar29, dVar30, dVar31, dVar32, dVar33, dVar34, dVar35, dVar36, dVar37, dVar38, dVar39, dVar40, dVar41, dVar42, dVar43, dVar44, dVar45, dVar46, dVar47, dVar48, dVar49, dVar50, dVar51, dVar52, dVar53, dVar54, dVar55, dVar56, dVar57, dVar58, dVar59, dVar60, dVar61, dVar62, dVar63, dVar64, dVar65, dVar66, dVar67, dVar68, dVar69, dVar70, dVar71, dVar72, dVar73, dVar74, dVar75, dVar76, dVar77, dVar78, dVar79, dVar80, dVar81, dVar82, dVar83, dVar84, dVar85, dVar86, dVar87, dVar88, dVar89, dVar90, dVar91, dVar92, dVar93, dVar94, dVar95, dVar96, dVar97, dVar98, dVar99, dVar100, dVar101, dVar102, dVar103, dVar104, dVar105, dVar106, dVar107, dVar108, dVar109, dVar110, dVar111, dVar112, dVar113, dVar114, dVar115, dVar116, dVar117, dVar118, dVar119, dVar120, dVar121, dVar122, dVar123, dVar124, dVar125, dVar126, dVar127, dVar128, dVar129, dVar130, dVar131, dVar132, dVar133, dVar134, dVar135, dVar136, dVar137, dVar138, dVar139, dVar140, dVar141, dVar142, dVar143, dVar144, dVar145, dVar146, dVar147, dVar148, dVar149, dVar150, dVar151, dVar152, dVar153, dVar154, dVar155, dVar156, dVar157, dVar158, dVar159, dVar160, dVar161};
        $VALUES = dVarArr;
        $ENTRIES = new a80.b(dVarArr);
    }

    public d(String str, int i11, String str2) {
        this.value = str2;
    }

    public static d valueOf(String str) {
        return (d) Enum.valueOf(d.class, str);
    }

    public static d[] values() {
        return (d[]) $VALUES.clone();
    }

    public final String a() {
        return this.value;
    }
}
