package com.adyen.checkout.core.internal.util;

import android.os.Parcel;
import i4.a;
import kotlin.Metadata;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.json.JSONObject;
import u70.n;

/* JADX INFO: compiled from: r8-map-id-bad8e3e1b75e2d3fd72c92f1b960553adb24fef824cc9e98cee450b85845d4c2 */
/* JADX INFO: loaded from: classes.dex */
@Metadata(d1 = {"\u0000&\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\b\n\u0000\n\u0002\u0010\u0002\n\u0002\b\u0006\bÇ\u0002\u0018\u00002\n\u0012\u0006\u0012\u0004\u0018\u00010\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u0019\u0010\u0007\u001a\u0004\u0018\u00010\u00022\u0006\u0010\u0006\u001a\u00020\u0005H\u0016¢\u0006\u0004\b\u0007\u0010\bJ%\u0010\f\u001a\u00020\u000b*\u0004\u0018\u00010\u00022\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\n\u001a\u00020\tH\u0016¢\u0006\u0004\b\f\u0010\rR\u0014\u0010\u000e\u001a\u00020\t8\u0002X\u0082T¢\u0006\u0006\n\u0004\b\u000e\u0010\u000fR\u0014\u0010\u0010\u001a\u00020\t8\u0002X\u0082T¢\u0006\u0006\n\u0004\b\u0010\u0010\u000f¨\u0006\u0011"}, d2 = {"Lcom/adyen/checkout/core/internal/util/JSONObjectParceler;", "", "Lorg/json/JSONObject;", "<init>", "()V", "Landroid/os/Parcel;", "parcel", "create", "(Landroid/os/Parcel;)Lorg/json/JSONObject;", "", "flags", "", "write", "(Lorg/json/JSONObject;Landroid/os/Parcel;I)V", "FLAG_NULL", "I", "FLAG_NON_NULL", "checkout-core_release"}, k = 1, mv = {1, 9, 0}, xi = 48)
public final class JSONObjectParceler {
    private static final int FLAG_NON_NULL = 1;
    private static final int FLAG_NULL = 0;

    @NotNull
    public static final JSONObjectParceler INSTANCE = new JSONObjectParceler();

    private JSONObjectParceler() {
    }

    @Nullable
    public JSONObject create(@NotNull Parcel parcel) {
        parcel.getClass();
        int i11 = parcel.readInt();
        if (i11 == 0) {
            return null;
        }
        if (i11 != 1) {
            a.f("Invalid flag.");
            return null;
        }
        String string = parcel.readString();
        if (string == null) {
            string = "";
        }
        return new JSONObject(string);
    }

    @NotNull
    public JSONObject[] newArray(int i11) {
        throw new n("Generated by Android Extensions automatically");
    }

    public void write(@Nullable JSONObject jSONObject, @NotNull Parcel parcel, int i11) {
        parcel.getClass();
        if (jSONObject == null) {
            parcel.writeInt(0);
        } else {
            parcel.writeInt(1);
            parcel.writeString(jSONObject.toString());
        }
    }
}
