package com.app.tgtg.model.remote.order;

import c50.w;
import com.app.tgtg.model.remote.ItemId;
import com.app.tgtg.model.remote.ItemId$$serializer;
import com.app.tgtg.model.remote.OrderId;
import com.app.tgtg.model.remote.OrderId$$serializer;
import com.app.tgtg.model.remote.StoreId;
import com.app.tgtg.model.remote.StoreId$$serializer;
import com.app.tgtg.model.remote.UserId;
import com.app.tgtg.model.remote.UserId$$serializer;
import com.app.tgtg.model.remote.item.ItemCategory;
import com.app.tgtg.model.remote.item.ItemCategorySerializer;
import com.app.tgtg.model.remote.item.PickupInterval;
import com.app.tgtg.model.remote.item.PickupInterval$$serializer;
import com.app.tgtg.model.remote.item.Picture;
import com.app.tgtg.model.remote.item.Picture$$serializer;
import com.app.tgtg.model.remote.item.StoreLocation;
import com.app.tgtg.model.remote.item.StoreLocation$$serializer;
import com.app.tgtg.model.remote.item.response.CancellingEntity;
import com.app.tgtg.model.remote.item.response.CancellingEntitySerializer;
import com.app.tgtg.model.remote.item.response.PackagingOptions;
import com.app.tgtg.model.remote.item.response.PaymentState;
import com.app.tgtg.model.remote.item.response.PaymentStateEnumSerializer;
import com.app.tgtg.model.remote.payment.Price;
import com.app.tgtg.model.remote.payment.Price$$serializer;
import com.appsflyer.attribution.RequestError;
import i90.b;
import java.util.List;
import kotlin.Metadata;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import l90.a;
import m90.c1;
import m90.d0;
import m90.e1;
import m90.g;
import m90.l0;
import m90.r1;
import m90.v;
import o30.f0;
import org.bouncycastle.asn1.BERTags;
import org.bouncycastle.iana.AEADAlgorithm;
import org.bouncycastle.pqc.crypto.newhope.NewHope;
import org.brotli.dec.BrotliInputStream;
import org.jetbrains.annotations.NotNull;
import u70.d;
import u70.j;

/* JADX INFO: compiled from: r8-map-id-bad8e3e1b75e2d3fd72c92f1b960553adb24fef824cc9e98cee450b85845d4c2 */
/* JADX INFO: loaded from: classes2.dex */
@Metadata(d1 = {"\u0000:\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u0003\u0010\u0004J\u001d\u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002¢\u0006\u0004\b\t\u0010\nJ\u0015\u0010\r\u001a\u00020\u00022\u0006\u0010\f\u001a\u00020\u000b¢\u0006\u0004\b\r\u0010\u000eJ\u0017\u0010\u0011\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\u00100\u000f¢\u0006\u0004\b\u0011\u0010\u0012R\u0017\u0010\u0014\u001a\u00020\u00138\u0006¢\u0006\f\n\u0004\b\u0014\u0010\u0015\u001a\u0004\b\u0016\u0010\u0017¨\u0006\u0018"}, d2 = {"com/app/tgtg/model/remote/order/Order.$serializer", "Lm90/d0;", "Lcom/app/tgtg/model/remote/order/Order;", "<init>", "()V", "Lkotlinx/serialization/encoding/Encoder;", "encoder", "value", "", "serialize", "(Lkotlinx/serialization/encoding/Encoder;Lcom/app/tgtg/model/remote/order/Order;)V", "Lkotlinx/serialization/encoding/Decoder;", "decoder", "deserialize", "(Lkotlinx/serialization/encoding/Decoder;)Lcom/app/tgtg/model/remote/order/Order;", "", "Lkotlinx/serialization/KSerializer;", "childSerializers", "()[Lkotlinx/serialization/KSerializer;", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "app"}, k = 1, mv = {2, 3, 0}, xi = 48)
@d
public final /* synthetic */ class Order$$serializer implements d0 {
    public static final int $stable;

    @NotNull
    public static final Order$$serializer INSTANCE;

    @NotNull
    private static final SerialDescriptor descriptor;

    static {
        Order$$serializer order$$serializer = new Order$$serializer();
        INSTANCE = order$$serializer;
        $stable = 8;
        e1 e1Var = new e1("com.app.tgtg.model.remote.order.Order", order$$serializer, 62);
        e1Var.j("cancel_until", true);
        e1Var.j("confirmation_email_sent_to", false);
        e1Var.j("food_handling_instructions", false);
        e1Var.j("buffet_instructions", false);
        e1Var.j("can_user_supply_packaging", true);
        e1Var.j("packaging_option", true);
        e1Var.j("is_rated", true);
        e1Var.j("can_be_rated", true);
        e1Var.j("item_collection_info", false);
        e1Var.j("item_cover_image", false);
        e1Var.j("item_logo", false);
        e1Var.j("item_id", false);
        e1Var.j("item_name", false);
        e1Var.j("pickup_interval", false);
        e1Var.j("pickup_location", false);
        e1Var.j("store_time_zone", false);
        e1Var.j("price", false);
        e1Var.j("total_price", false);
        e1Var.j("quantity", false);
        e1Var.j("overall_rating", false);
        e1Var.j("order_id", false);
        e1Var.j("redeem_interval", false);
        e1Var.j("state", false);
        e1Var.j("store_branch", false);
        e1Var.j("store_id", false);
        e1Var.j("store_logo", false);
        e1Var.j("store_name", false);
        e1Var.j("time_of_purchase", false);
        e1Var.j("is_buffet", true);
        e1Var.j("can_show_best_before_explainer", true);
        e1Var.j("order_type", false);
        e1Var.j("pickup_window_changed", true);
        e1Var.j("additional_order_details", false);
        e1Var.j("payment_method_display_name", false);
        e1Var.j("cancelled_or_refunded_at_utc", false);
        e1Var.j("redeemed_at_utc", false);
        e1Var.j("support_request_created_at_utc", false);
        e1Var.j("expected_bank_processing_days", true);
        e1Var.j("payment_state", false);
        e1Var.j("cancelling_entity", false);
        e1Var.j("is_support_available", true);
        e1Var.j("should_be_excluded_from_expense_rating", true);
        e1Var.j("needsSync", true);
        e1Var.j("hasCollectionTimeChanged", true);
        e1Var.j("hasCollectionStateChanged", true);
        e1Var.j("calendarEventId", true);
        e1Var.j("has_dynamic_price", true);
        e1Var.j("invitation_id", false);
        e1Var.j("redeeming_user_id", false);
        e1Var.j("is_donation", true);
        e1Var.j("is_eligible_for_reward", true);
        e1Var.j("has_multiple_payments", true);
        e1Var.j("total_price_paid_with_external_provider", false);
        e1Var.j("total_price_paid_with_voucher", false);
        e1Var.j("item_category", false);
        e1Var.j("is_favorite", false);
        e1Var.j("is_multi_item", false);
        e1Var.j("is_edible", true);
        e1Var.j("order_items", false);
        e1Var.j("specification_lines", false);
        e1Var.j("total_price_paid_for_delivery", false);
        e1Var.j("discount_applied_percentage", true);
        descriptor = e1Var;
    }

    private Order$$serializer() {
    }

    /* JADX WARN: Multi-variable type inference failed */
    @Override // m90.d0
    @NotNull
    public final KSerializer[] childSerializers() {
        j[] jVarArr = Order.$childSerializers;
        r1 r1Var = r1.f29848a;
        g gVar = g.f29797a;
        Picture$$serializer picture$$serializer = Picture$$serializer.INSTANCE;
        PickupInterval$$serializer pickupInterval$$serializer = PickupInterval$$serializer.INSTANCE;
        Price$$serializer price$$serializer = Price$$serializer.INSTANCE;
        l0 l0Var = l0.f29821a;
        return new KSerializer[]{f0.B(r1Var), f0.B(r1Var), f0.B(r1Var), f0.B(r1Var), gVar, jVarArr[5].getValue(), gVar, gVar, f0.B(r1Var), f0.B(picture$$serializer), f0.B(picture$$serializer), f0.B(ItemId$$serializer.INSTANCE), f0.B(r1Var), f0.B(pickupInterval$$serializer), f0.B(StoreLocation$$serializer.INSTANCE), f0.B(r1Var), f0.B(price$$serializer), price$$serializer, l0Var, f0.B(l0Var), OrderId$$serializer.INSTANCE, f0.B(pickupInterval$$serializer), OrderStateSerializer.INSTANCE, f0.B(r1Var), StoreId$$serializer.INSTANCE, f0.B(picture$$serializer), f0.B(r1Var), r1Var, gVar, gVar, OrderTypeSerializer.INSTANCE, gVar, f0.B(AdditionalOrderInformation$$serializer.INSTANCE), f0.B(r1Var), f0.B(r1Var), f0.B(r1Var), f0.B(r1Var), l0Var, f0.B(PaymentStateEnumSerializer.INSTANCE), f0.B(CancellingEntitySerializer.INSTANCE), gVar, gVar, f0.B(gVar), gVar, gVar, l0Var, f0.B(gVar), f0.B(r1Var), f0.B(UserId$$serializer.INSTANCE), gVar, gVar, gVar, f0.B(price$$serializer), f0.B(price$$serializer), f0.B(ItemCategorySerializer.INSTANCE), f0.B(gVar), f0.B(gVar), gVar, f0.B((KSerializer) jVarArr[58].getValue()), f0.B((KSerializer) jVarArr[59].getValue()), f0.B(price$$serializer), f0.B(v.f29868a)};
    }

    @Override // i90.b
    @NotNull
    public final Order deserialize(@NotNull Decoder decoder) {
        String str;
        int i11;
        String str2;
        List list;
        int i12;
        Boolean bool;
        String str3;
        StoreLocation storeLocation;
        List list2;
        CancellingEntity cancellingEntity;
        String str4;
        List list3;
        List list4;
        CancellingEntity cancellingEntity2;
        StoreLocation storeLocation2;
        String str5;
        Boolean bool2;
        int i13;
        List list5;
        List list6;
        CancellingEntity cancellingEntity3;
        String str6;
        int i14;
        List list7;
        List list8;
        CancellingEntity cancellingEntity4;
        int i15;
        int i16;
        CancellingEntity cancellingEntity5;
        CancellingEntity cancellingEntity6;
        CancellingEntity cancellingEntity7;
        Boolean bool3;
        decoder.getClass();
        SerialDescriptor serialDescriptor = descriptor;
        a aVarC = decoder.c(serialDescriptor);
        j[] jVarArr = Order.$childSerializers;
        List list9 = null;
        List list10 = null;
        int i17 = 0;
        Boolean bool4 = null;
        Price price = null;
        Price price2 = null;
        Boolean bool5 = null;
        Price price3 = null;
        Double d3 = null;
        CancellingEntity cancellingEntity8 = null;
        Boolean bool6 = null;
        Boolean bool7 = null;
        ItemCategory itemCategory = null;
        String str7 = null;
        boolean z11 = true;
        String str8 = null;
        String strM205unboximpl = null;
        String str9 = null;
        String str10 = null;
        String str11 = null;
        PackagingOptions packagingOptions = null;
        String str12 = null;
        Picture picture = null;
        Picture picture2 = null;
        String str13 = null;
        String strM217unboximpl = null;
        PickupInterval pickupInterval = null;
        int i18 = 0;
        StoreLocation storeLocation3 = null;
        String strM277unboximpl = null;
        String str14 = null;
        Price price4 = null;
        Price price5 = null;
        Integer num = null;
        PickupInterval pickupInterval2 = null;
        OrderState orderState = null;
        String str15 = null;
        Picture picture3 = null;
        String str16 = null;
        OrderType orderType = null;
        AdditionalOrderInformation additionalOrderInformation = null;
        String str17 = null;
        String str18 = null;
        String str19 = null;
        String str20 = null;
        PaymentState paymentState = null;
        boolean zT = false;
        boolean zT2 = false;
        boolean zT3 = false;
        int iQ = 0;
        String strU = null;
        boolean zT4 = false;
        boolean zT5 = false;
        String strM294unboximpl = null;
        boolean zT6 = false;
        int iQ2 = 0;
        boolean zT7 = false;
        boolean zT8 = false;
        boolean zT9 = false;
        boolean zT10 = false;
        int iQ3 = 0;
        boolean zT11 = false;
        boolean zT12 = false;
        boolean zT13 = false;
        boolean zT14 = false;
        while (z11) {
            int iW = aVarC.w(serialDescriptor);
            switch (iW) {
                case -1:
                    CancellingEntity cancellingEntity9 = cancellingEntity8;
                    str = str9;
                    String str21 = str15;
                    i11 = i17;
                    str12 = str12;
                    bool4 = bool4;
                    storeLocation3 = storeLocation3;
                    i18 = i18;
                    z11 = false;
                    list10 = list10;
                    list9 = list9;
                    str2 = str21;
                    cancellingEntity8 = cancellingEntity9;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 0:
                    list = list10;
                    CancellingEntity cancellingEntity10 = cancellingEntity8;
                    String str22 = str15;
                    i11 = i17;
                    str = str9;
                    i12 = i18 | 1;
                    str8 = (String) aVarC.m(serialDescriptor, 0, r1.f29848a, str8);
                    str12 = str12;
                    bool4 = bool4;
                    list9 = list9;
                    str2 = str22;
                    storeLocation3 = storeLocation3;
                    cancellingEntity8 = cancellingEntity10;
                    i18 = i12;
                    list10 = list;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 1:
                    CancellingEntity cancellingEntity11 = cancellingEntity8;
                    String str23 = str15;
                    i11 = i17;
                    str = (String) aVarC.m(serialDescriptor, 1, r1.f29848a, str9);
                    str12 = str12;
                    str10 = str10;
                    bool4 = bool4;
                    list10 = list10;
                    list9 = list9;
                    str2 = str23;
                    storeLocation3 = storeLocation3;
                    cancellingEntity8 = cancellingEntity11;
                    i18 |= 2;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 2:
                    StoreLocation storeLocation4 = storeLocation3;
                    bool = bool4;
                    str3 = str12;
                    int i19 = i18;
                    storeLocation = storeLocation4;
                    list2 = list9;
                    list = list10;
                    cancellingEntity = cancellingEntity8;
                    str4 = str15;
                    i11 = i17;
                    i12 = i19 | 4;
                    str10 = (String) aVarC.m(serialDescriptor, 2, r1.f29848a, str10);
                    str12 = str3;
                    str2 = str4;
                    str = str9;
                    bool4 = bool;
                    cancellingEntity8 = cancellingEntity;
                    list9 = list2;
                    storeLocation3 = storeLocation;
                    i18 = i12;
                    list10 = list;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 3:
                    StoreLocation storeLocation5 = storeLocation3;
                    bool = bool4;
                    str3 = str12;
                    int i21 = i18;
                    storeLocation = storeLocation5;
                    list2 = list9;
                    list = list10;
                    cancellingEntity = cancellingEntity8;
                    str4 = str15;
                    i11 = i17;
                    i12 = i21 | 8;
                    str11 = (String) aVarC.m(serialDescriptor, 3, r1.f29848a, str11);
                    str12 = str3;
                    str2 = str4;
                    str = str9;
                    bool4 = bool;
                    cancellingEntity8 = cancellingEntity;
                    list9 = list2;
                    storeLocation3 = storeLocation;
                    i18 = i12;
                    list10 = list;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 4:
                    StoreLocation storeLocation6 = storeLocation3;
                    bool = bool4;
                    str3 = str12;
                    int i22 = i18;
                    storeLocation = storeLocation6;
                    list2 = list9;
                    list = list10;
                    cancellingEntity = cancellingEntity8;
                    str4 = str15;
                    i11 = i17;
                    zT = aVarC.t(serialDescriptor, 4);
                    i12 = i22 | 16;
                    str12 = str3;
                    str2 = str4;
                    str = str9;
                    bool4 = bool;
                    cancellingEntity8 = cancellingEntity;
                    list9 = list2;
                    storeLocation3 = storeLocation;
                    i18 = i12;
                    list10 = list;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 5:
                    list2 = list9;
                    list = list10;
                    cancellingEntity = cancellingEntity8;
                    int i23 = i18;
                    storeLocation = storeLocation3;
                    str4 = str15;
                    i11 = i17;
                    bool = bool4;
                    str3 = str12;
                    i12 = i23 | 32;
                    packagingOptions = (PackagingOptions) aVarC.n(serialDescriptor, 5, (b) jVarArr[5].getValue(), packagingOptions);
                    str12 = str3;
                    str2 = str4;
                    str = str9;
                    bool4 = bool;
                    cancellingEntity8 = cancellingEntity;
                    list9 = list2;
                    storeLocation3 = storeLocation;
                    i18 = i12;
                    list10 = list;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 6:
                    list3 = list9;
                    list4 = list10;
                    cancellingEntity2 = cancellingEntity8;
                    int i24 = i18;
                    storeLocation2 = storeLocation3;
                    str5 = str15;
                    i11 = i17;
                    bool2 = bool4;
                    zT2 = aVarC.t(serialDescriptor, 6);
                    i13 = i24 | 64;
                    str2 = str5;
                    str = str9;
                    bool4 = bool2;
                    cancellingEntity8 = cancellingEntity2;
                    list10 = list4;
                    storeLocation3 = storeLocation2;
                    i18 = i13;
                    list9 = list3;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 7:
                    list3 = list9;
                    list4 = list10;
                    cancellingEntity2 = cancellingEntity8;
                    int i25 = i18;
                    storeLocation2 = storeLocation3;
                    str5 = str15;
                    i11 = i17;
                    bool2 = bool4;
                    zT3 = aVarC.t(serialDescriptor, 7);
                    i13 = i25 | 128;
                    str2 = str5;
                    str = str9;
                    bool4 = bool2;
                    cancellingEntity8 = cancellingEntity2;
                    list10 = list4;
                    storeLocation3 = storeLocation2;
                    i18 = i13;
                    list9 = list3;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 8:
                    list3 = list9;
                    list4 = list10;
                    cancellingEntity2 = cancellingEntity8;
                    int i26 = i18;
                    storeLocation2 = storeLocation3;
                    str5 = str15;
                    i11 = i17;
                    bool2 = bool4;
                    i13 = i26 | 256;
                    str12 = (String) aVarC.m(serialDescriptor, 8, r1.f29848a, str12);
                    str2 = str5;
                    str = str9;
                    bool4 = bool2;
                    cancellingEntity8 = cancellingEntity2;
                    list10 = list4;
                    storeLocation3 = storeLocation2;
                    i18 = i13;
                    list9 = list3;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 9:
                    list3 = list9;
                    list4 = list10;
                    cancellingEntity2 = cancellingEntity8;
                    int i27 = i18;
                    storeLocation2 = storeLocation3;
                    str5 = str15;
                    i11 = i17;
                    bool2 = bool4;
                    i13 = i27 | 512;
                    picture = (Picture) aVarC.m(serialDescriptor, 9, Picture$$serializer.INSTANCE, picture);
                    str2 = str5;
                    str = str9;
                    bool4 = bool2;
                    cancellingEntity8 = cancellingEntity2;
                    list10 = list4;
                    storeLocation3 = storeLocation2;
                    i18 = i13;
                    list9 = list3;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 10:
                    list3 = list9;
                    list4 = list10;
                    cancellingEntity2 = cancellingEntity8;
                    int i28 = i18;
                    storeLocation2 = storeLocation3;
                    str5 = str15;
                    i11 = i17;
                    bool2 = bool4;
                    i13 = i28 | 1024;
                    picture2 = (Picture) aVarC.m(serialDescriptor, 10, Picture$$serializer.INSTANCE, picture2);
                    str2 = str5;
                    str = str9;
                    bool4 = bool2;
                    cancellingEntity8 = cancellingEntity2;
                    list10 = list4;
                    storeLocation3 = storeLocation2;
                    i18 = i13;
                    list9 = list3;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 11:
                    list3 = list9;
                    list4 = list10;
                    cancellingEntity2 = cancellingEntity8;
                    int i29 = i18;
                    storeLocation2 = storeLocation3;
                    str5 = str15;
                    i11 = i17;
                    bool2 = bool4;
                    str13 = str13;
                    ItemId itemId = (ItemId) aVarC.m(serialDescriptor, 11, ItemId$$serializer.INSTANCE, strM205unboximpl != null ? ItemId.m197boximpl(strM205unboximpl) : null);
                    strM205unboximpl = itemId != null ? itemId.m205unboximpl() : null;
                    i13 = i29 | NewHope.SENDB_BYTES;
                    str2 = str5;
                    str = str9;
                    bool4 = bool2;
                    cancellingEntity8 = cancellingEntity2;
                    list10 = list4;
                    storeLocation3 = storeLocation2;
                    i18 = i13;
                    list9 = list3;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 12:
                    list3 = list9;
                    list4 = list10;
                    cancellingEntity2 = cancellingEntity8;
                    int i31 = i18;
                    storeLocation2 = storeLocation3;
                    str5 = str15;
                    i11 = i17;
                    bool2 = bool4;
                    i13 = i31 | 4096;
                    str13 = (String) aVarC.m(serialDescriptor, 12, r1.f29848a, str13);
                    str2 = str5;
                    str = str9;
                    bool4 = bool2;
                    cancellingEntity8 = cancellingEntity2;
                    list10 = list4;
                    storeLocation3 = storeLocation2;
                    i18 = i13;
                    list9 = list3;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 13:
                    list3 = list9;
                    list4 = list10;
                    cancellingEntity2 = cancellingEntity8;
                    int i32 = i18;
                    str5 = str15;
                    i11 = i17;
                    storeLocation2 = storeLocation3;
                    bool2 = bool4;
                    i13 = i32 | 8192;
                    pickupInterval = (PickupInterval) aVarC.m(serialDescriptor, 13, PickupInterval$$serializer.INSTANCE, pickupInterval);
                    str2 = str5;
                    str = str9;
                    bool4 = bool2;
                    cancellingEntity8 = cancellingEntity2;
                    list10 = list4;
                    storeLocation3 = storeLocation2;
                    i18 = i13;
                    list9 = list3;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 14:
                    list5 = list9;
                    list6 = list10;
                    cancellingEntity3 = cancellingEntity8;
                    str6 = str15;
                    i11 = i17;
                    StoreLocation storeLocation7 = (StoreLocation) aVarC.m(serialDescriptor, 14, StoreLocation$$serializer.INSTANCE, storeLocation3);
                    i18 |= BrotliInputStream.DEFAULT_INTERNAL_BUFFER_SIZE;
                    storeLocation3 = storeLocation7;
                    str2 = str6;
                    str = str9;
                    cancellingEntity8 = cancellingEntity3;
                    list10 = list6;
                    list9 = list5;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case AEADAlgorithm.AEAD_AES_SIV_CMAC_256 /* 15 */:
                    list5 = list9;
                    list6 = list10;
                    cancellingEntity3 = cancellingEntity8;
                    str6 = str15;
                    i11 = i17;
                    i14 = i18 | 32768;
                    str14 = (String) aVarC.m(serialDescriptor, 15, r1.f29848a, str14);
                    i18 = i14;
                    str2 = str6;
                    str = str9;
                    cancellingEntity8 = cancellingEntity3;
                    list10 = list6;
                    list9 = list5;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 16:
                    list5 = list9;
                    list6 = list10;
                    cancellingEntity3 = cancellingEntity8;
                    str6 = str15;
                    i11 = i17;
                    i14 = i18 | 65536;
                    price4 = (Price) aVarC.m(serialDescriptor, 16, Price$$serializer.INSTANCE, price4);
                    i18 = i14;
                    str2 = str6;
                    str = str9;
                    cancellingEntity8 = cancellingEntity3;
                    list10 = list6;
                    list9 = list5;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 17:
                    list5 = list9;
                    list6 = list10;
                    cancellingEntity3 = cancellingEntity8;
                    str6 = str15;
                    i11 = i17;
                    i14 = i18 | 131072;
                    price5 = (Price) aVarC.n(serialDescriptor, 17, Price$$serializer.INSTANCE, price5);
                    i18 = i14;
                    str2 = str6;
                    str = str9;
                    cancellingEntity8 = cancellingEntity3;
                    list10 = list6;
                    list9 = list5;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 18:
                    list5 = list9;
                    CancellingEntity cancellingEntity12 = cancellingEntity8;
                    String str24 = str15;
                    i11 = i17;
                    iQ = aVarC.q(serialDescriptor, 18);
                    i18 |= 262144;
                    str2 = str24;
                    str = str9;
                    cancellingEntity8 = cancellingEntity12;
                    list9 = list5;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 19:
                    list5 = list9;
                    list6 = list10;
                    cancellingEntity3 = cancellingEntity8;
                    str6 = str15;
                    i11 = i17;
                    i14 = i18 | 524288;
                    num = (Integer) aVarC.m(serialDescriptor, 19, l0.f29821a, num);
                    i18 = i14;
                    str2 = str6;
                    str = str9;
                    cancellingEntity8 = cancellingEntity3;
                    list10 = list6;
                    list9 = list5;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 20:
                    list5 = list9;
                    list6 = list10;
                    cancellingEntity3 = cancellingEntity8;
                    str6 = str15;
                    i11 = i17;
                    pickupInterval2 = pickupInterval2;
                    OrderId orderId = (OrderId) aVarC.n(serialDescriptor, 20, OrderId$$serializer.INSTANCE, strM217unboximpl != null ? OrderId.m209boximpl(strM217unboximpl) : null);
                    strM217unboximpl = orderId != null ? orderId.m217unboximpl() : null;
                    i18 |= 1048576;
                    str2 = str6;
                    str = str9;
                    cancellingEntity8 = cancellingEntity3;
                    list10 = list6;
                    list9 = list5;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 21:
                    list5 = list9;
                    list6 = list10;
                    cancellingEntity3 = cancellingEntity8;
                    str6 = str15;
                    i11 = i17;
                    i14 = i18 | 2097152;
                    pickupInterval2 = (PickupInterval) aVarC.m(serialDescriptor, 21, PickupInterval$$serializer.INSTANCE, pickupInterval2);
                    i18 = i14;
                    str2 = str6;
                    str = str9;
                    cancellingEntity8 = cancellingEntity3;
                    list10 = list6;
                    list9 = list5;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 22:
                    list5 = list9;
                    list6 = list10;
                    cancellingEntity3 = cancellingEntity8;
                    str6 = str15;
                    i11 = i17;
                    i14 = i18 | 4194304;
                    orderState = (OrderState) aVarC.n(serialDescriptor, 22, OrderStateSerializer.INSTANCE, orderState);
                    i18 = i14;
                    str2 = str6;
                    str = str9;
                    cancellingEntity8 = cancellingEntity3;
                    list10 = list6;
                    list9 = list5;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 23:
                    list5 = list9;
                    list6 = list10;
                    cancellingEntity3 = cancellingEntity8;
                    str2 = (String) aVarC.m(serialDescriptor, 23, r1.f29848a, str15);
                    i18 |= 8388608;
                    i11 = i17;
                    str = str9;
                    cancellingEntity8 = cancellingEntity3;
                    list10 = list6;
                    list9 = list5;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 24:
                    list7 = list9;
                    list8 = list10;
                    cancellingEntity4 = cancellingEntity8;
                    picture3 = picture3;
                    StoreId storeId = (StoreId) aVarC.n(serialDescriptor, 24, StoreId$$serializer.INSTANCE, strM277unboximpl != null ? StoreId.m269boximpl(strM277unboximpl) : null);
                    strM277unboximpl = storeId != null ? storeId.m277unboximpl() : null;
                    i18 |= 16777216;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity4;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 25:
                    list7 = list9;
                    list8 = list10;
                    cancellingEntity4 = cancellingEntity8;
                    i15 = i18 | 33554432;
                    picture3 = (Picture) aVarC.m(serialDescriptor, 25, Picture$$serializer.INSTANCE, picture3);
                    i18 = i15;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity4;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 26:
                    list7 = list9;
                    list8 = list10;
                    cancellingEntity4 = cancellingEntity8;
                    i15 = i18 | 67108864;
                    str16 = (String) aVarC.m(serialDescriptor, 26, r1.f29848a, str16);
                    i18 = i15;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity4;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 27:
                    list7 = list9;
                    list8 = list10;
                    strU = aVarC.u(serialDescriptor, 27);
                    i16 = i18 | 134217728;
                    i18 = i16;
                    str = str9;
                    str2 = str15;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 28:
                    list7 = list9;
                    list8 = list10;
                    zT4 = aVarC.t(serialDescriptor, 28);
                    i16 = i18 | 268435456;
                    i18 = i16;
                    str = str9;
                    str2 = str15;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 29:
                    list7 = list9;
                    list8 = list10;
                    zT5 = aVarC.t(serialDescriptor, 29);
                    i16 = i18 | 536870912;
                    i18 = i16;
                    str = str9;
                    str2 = str15;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 30:
                    list7 = list9;
                    list8 = list10;
                    cancellingEntity4 = cancellingEntity8;
                    i15 = i18 | 1073741824;
                    orderType = (OrderType) aVarC.n(serialDescriptor, 30, OrderTypeSerializer.INSTANCE, orderType);
                    i18 = i15;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity4;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case BERTags.DATE /* 31 */:
                    list7 = list9;
                    list8 = list10;
                    zT6 = aVarC.t(serialDescriptor, 31);
                    i16 = i18 | Integer.MIN_VALUE;
                    i18 = i16;
                    str = str9;
                    str2 = str15;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 32:
                    list7 = list9;
                    list8 = list10;
                    cancellingEntity4 = cancellingEntity8;
                    i17 |= 1;
                    additionalOrderInformation = (AdditionalOrderInformation) aVarC.m(serialDescriptor, 32, AdditionalOrderInformation$$serializer.INSTANCE, additionalOrderInformation);
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity4;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 33:
                    list7 = list9;
                    list8 = list10;
                    cancellingEntity4 = cancellingEntity8;
                    i17 |= 2;
                    str17 = (String) aVarC.m(serialDescriptor, 33, r1.f29848a, str17);
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity4;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case BERTags.DURATION /* 34 */:
                    list7 = list9;
                    list8 = list10;
                    cancellingEntity4 = cancellingEntity8;
                    i17 |= 4;
                    str18 = (String) aVarC.m(serialDescriptor, 34, r1.f29848a, str18);
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity4;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case BERTags.OBJECT_IDENTIFIER_IRI /* 35 */:
                    list7 = list9;
                    list8 = list10;
                    cancellingEntity4 = cancellingEntity8;
                    i17 |= 8;
                    str19 = (String) aVarC.m(serialDescriptor, 35, r1.f29848a, str19);
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity4;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 36:
                    list7 = list9;
                    list8 = list10;
                    cancellingEntity4 = cancellingEntity8;
                    i17 |= 16;
                    str20 = (String) aVarC.m(serialDescriptor, 36, r1.f29848a, str20);
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity4;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 37:
                    list7 = list9;
                    list8 = list10;
                    iQ2 = aVarC.q(serialDescriptor, 37);
                    i17 |= 32;
                    str = str9;
                    str2 = str15;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 38:
                    list7 = list9;
                    list8 = list10;
                    cancellingEntity4 = cancellingEntity8;
                    i17 |= 64;
                    paymentState = (PaymentState) aVarC.m(serialDescriptor, 38, PaymentStateEnumSerializer.INSTANCE, paymentState);
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity4;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 39:
                    list7 = list9;
                    list8 = list10;
                    cancellingEntity8 = (CancellingEntity) aVarC.m(serialDescriptor, 39, CancellingEntitySerializer.INSTANCE, cancellingEntity8);
                    i17 |= 128;
                    str = str9;
                    str2 = str15;
                    list10 = list8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 40:
                    list7 = list9;
                    zT7 = aVarC.t(serialDescriptor, 40);
                    i17 |= 256;
                    str = str9;
                    str2 = str15;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case RequestError.NO_DEV_KEY /* 41 */:
                    list7 = list9;
                    zT8 = aVarC.t(serialDescriptor, 41);
                    i17 |= 512;
                    str = str9;
                    str2 = str15;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 42:
                    list7 = list9;
                    cancellingEntity5 = cancellingEntity8;
                    bool6 = (Boolean) aVarC.m(serialDescriptor, 42, g.f29797a, bool6);
                    i17 |= 1024;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity5;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 43:
                    list7 = list9;
                    zT9 = aVarC.t(serialDescriptor, 43);
                    i17 |= NewHope.SENDB_BYTES;
                    str = str9;
                    str2 = str15;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 44:
                    list7 = list9;
                    zT10 = aVarC.t(serialDescriptor, 44);
                    i17 |= 4096;
                    str = str9;
                    str2 = str15;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 45:
                    list7 = list9;
                    iQ3 = aVarC.q(serialDescriptor, 45);
                    i17 |= 8192;
                    str = str9;
                    str2 = str15;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 46:
                    list7 = list9;
                    cancellingEntity5 = cancellingEntity8;
                    bool7 = (Boolean) aVarC.m(serialDescriptor, 46, g.f29797a, bool7);
                    i17 |= BrotliInputStream.DEFAULT_INTERNAL_BUFFER_SIZE;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity5;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 47:
                    list7 = list9;
                    cancellingEntity5 = cancellingEntity8;
                    str7 = (String) aVarC.m(serialDescriptor, 47, r1.f29848a, str7);
                    i17 |= 32768;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity5;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 48:
                    CancellingEntity cancellingEntity13 = cancellingEntity8;
                    Boolean bool8 = bool6;
                    list7 = list9;
                    UserId userId = (UserId) aVarC.m(serialDescriptor, 48, UserId$$serializer.INSTANCE, strM294unboximpl != null ? UserId.m286boximpl(strM294unboximpl) : null);
                    strM294unboximpl = userId != null ? userId.m294unboximpl() : null;
                    i17 |= 65536;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity13;
                    bool6 = bool8;
                    list9 = list7;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 49:
                    cancellingEntity6 = cancellingEntity8;
                    zT11 = aVarC.t(serialDescriptor, 49);
                    i17 |= 131072;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity6;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 50:
                    cancellingEntity6 = cancellingEntity8;
                    zT12 = aVarC.t(serialDescriptor, 50);
                    i17 |= 262144;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity6;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 51:
                    cancellingEntity6 = cancellingEntity8;
                    zT13 = aVarC.t(serialDescriptor, 51);
                    i17 |= 524288;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity6;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 52:
                    cancellingEntity7 = cancellingEntity8;
                    bool3 = bool6;
                    price2 = (Price) aVarC.m(serialDescriptor, 52, Price$$serializer.INSTANCE, price2);
                    i17 |= 1048576;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity7;
                    bool6 = bool3;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 53:
                    cancellingEntity7 = cancellingEntity8;
                    bool3 = bool6;
                    price3 = (Price) aVarC.m(serialDescriptor, 53, Price$$serializer.INSTANCE, price3);
                    i17 |= 2097152;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity7;
                    bool6 = bool3;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 54:
                    cancellingEntity7 = cancellingEntity8;
                    bool3 = bool6;
                    itemCategory = (ItemCategory) aVarC.m(serialDescriptor, 54, ItemCategorySerializer.INSTANCE, itemCategory);
                    i17 |= 4194304;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity7;
                    bool6 = bool3;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 55:
                    cancellingEntity7 = cancellingEntity8;
                    bool3 = bool6;
                    bool4 = (Boolean) aVarC.m(serialDescriptor, 55, g.f29797a, bool4);
                    i17 |= 8388608;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity7;
                    bool6 = bool3;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 56:
                    cancellingEntity7 = cancellingEntity8;
                    bool3 = bool6;
                    bool5 = (Boolean) aVarC.m(serialDescriptor, 56, g.f29797a, bool5);
                    i17 |= 16777216;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity7;
                    bool6 = bool3;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 57:
                    cancellingEntity6 = cancellingEntity8;
                    zT14 = aVarC.t(serialDescriptor, 57);
                    i17 |= 33554432;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity6;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 58:
                    cancellingEntity7 = cancellingEntity8;
                    bool3 = bool6;
                    list10 = (List) aVarC.m(serialDescriptor, 58, (b) jVarArr[58].getValue(), list10);
                    i17 |= 67108864;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity7;
                    bool6 = bool3;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 59:
                    cancellingEntity7 = cancellingEntity8;
                    bool3 = bool6;
                    list9 = (List) aVarC.m(serialDescriptor, 59, (b) jVarArr[59].getValue(), list9);
                    i17 |= 134217728;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity7;
                    bool6 = bool3;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 60:
                    cancellingEntity7 = cancellingEntity8;
                    bool3 = bool6;
                    price = (Price) aVarC.m(serialDescriptor, 60, Price$$serializer.INSTANCE, price);
                    i17 |= 268435456;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity7;
                    bool6 = bool3;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                case 61:
                    cancellingEntity7 = cancellingEntity8;
                    bool3 = bool6;
                    d3 = (Double) aVarC.m(serialDescriptor, 61, v.f29868a, d3);
                    i17 |= 536870912;
                    str = str9;
                    str2 = str15;
                    cancellingEntity8 = cancellingEntity7;
                    bool6 = bool3;
                    i11 = i17;
                    str9 = str;
                    i17 = i11;
                    str15 = str2;
                    break;
                default:
                    w.e(iW);
                    return null;
            }
        }
        StoreLocation storeLocation8 = storeLocation3;
        Boolean bool9 = bool4;
        String str25 = str12;
        List list11 = list9;
        CancellingEntity cancellingEntity14 = cancellingEntity8;
        String str26 = str8;
        String str27 = str9;
        String str28 = str10;
        String str29 = str15;
        int i33 = i17;
        aVarC.b(serialDescriptor);
        return new Order(i18, i33, str26, str27, str28, str11, zT, packagingOptions, zT2, zT3, str25, picture, picture2, strM205unboximpl, str13, pickupInterval, storeLocation8, str14, price4, price5, iQ, num, strM217unboximpl, pickupInterval2, orderState, str29, strM277unboximpl, picture3, str16, strU, zT4, zT5, orderType, zT6, additionalOrderInformation, str17, str18, str19, str20, iQ2, paymentState, cancellingEntity14, zT7, zT8, bool6, zT9, zT10, iQ3, bool7, str7, strM294unboximpl, zT11, zT12, zT13, price2, price3, itemCategory, bool9, bool5, zT14, list10, list11, price, d3, null, null);
    }

    @Override // i90.b
    @NotNull
    public final SerialDescriptor getDescriptor() {
        return descriptor;
    }

    @Override // kotlinx.serialization.KSerializer
    public final void serialize(@NotNull Encoder encoder, @NotNull Order value) {
        encoder.getClass();
        value.getClass();
        SerialDescriptor serialDescriptor = descriptor;
        l90.b bVarC = encoder.c(serialDescriptor);
        Order.write$Self$app(value, bVarC, serialDescriptor);
        bVarC.b(serialDescriptor);
    }

    @Override // m90.d0
    @NotNull
    public /* bridge */ KSerializer[] typeParametersSerializers() {
        return c1.f29765b;
    }
}
